#!/usr/bin/env -S uv run --no-project python
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Render this repository's Codex project configuration.

ycli owns its own `.codex/`: `.codex/config.toml`, `.codex/hooks.json` and
`.codex/rules/` are generated by rulesync from the hand-edited `.rulesync/` canon
(see `rulesync.jsonc`). This file exists because the shared converter in
`bim-ba/agents` (`scripts/convert_claude_projects_to_codex.py`) treats the presence of
`tools/utils/codex_config/render.py` as the marker that a repository renders its own
`.codex/`, and skips it. Without the marker that converter would re-render
`.codex/config.toml` from `.mcp.json` and clobber rulesync's output — including turning
the `${VAR}` references back into values Codex cannot expand.

It is a real renderer, not a stub: it delegates to rulesync.

    uv run --no-project python tools/utils/codex_config/render.py
"""

from __future__ import annotations

import subprocess
import sys


def main() -> int:
    return subprocess.run(["rulesync", "generate", *sys.argv[1:]], check=False).returncode


if __name__ == "__main__":
    raise SystemExit(main())
