#!/usr/bin/env python
"""Generate README's Coverage section from the live code (a reproducible artifact).

Introspects the three domain clients **offline** (dummy credentials — constructing a client
builds only a ``requests.Session``, no HTTP) plus the committed public-surface data (the CLI
tree from :func:`tests.snapshots._surface.cli_tree` and the MCP tool-name snapshot
``tests/snapshots/mcp_tools.txt``) and emits the Markdown block README embeds between its
``COVERAGE:START`` / ``COVERAGE:END`` markers.

Per resource it reports the wrapped SDK operations (public methods on the resource client
class, in source order) and whether that resource is reachable via the CLI and via at least
one MCP tool. MCP mirrors the SDK with honest annotations (ARCH-3): reads carry
``readOnlyHint``, writes carry explicit destructive/idempotent hints; a resource with no MCP
tool yet shows ``—`` in the MCP column.

Usage::

    python scripts/gen_coverage.py            # print the block to stdout
    python scripts/gen_coverage.py --write    # splice it into README.md
    python scripts/gen_coverage.py --check     # exit 1 if README's block is stale

``--check`` powers ``tests/test_coverage_readme.py`` so the tables can never silently drift
from the code.
"""

from __future__ import annotations

import argparse
import inspect
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

import uplink.builder

from ycli.yandex.base import BaseYandex
from ycli.yandex.forms.client import FormsClient
from ycli.yandex.tracker.client import TrackerClient
from ycli.yandex.wiki.client import WikiClient

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
MCP_TOOLS = ROOT / "tests" / "snapshots" / "mcp_tools.txt"

# Committed map of resource/operation → public Yandex API-reference page (relative paths).
# The vendored api-ref under references/ is git-ignored, so the links live here, not there.
COVERAGE_URLS = ROOT / "scripts" / "coverage_urls.toml"
API_DOCS = "https://yandex.ru/support/{domain}/en/api-ref/{path}"

START = "<!-- COVERAGE:START (generated by scripts/gen_coverage.py — do not edit by hand) -->"
END = "<!-- COVERAGE:END -->"

YES = "✅"
NO = "—"

# Per-domain category → resource-attribute grouping. Every resource on a client must appear
# in exactly one group; a resource that is missing here lands in a trailing "Other" group so
# the omission is visible rather than silently dropped.
TRACKER_CATEGORIES: list[tuple[str, list[str]]] = [
    (
        "Issues & work items",
        [
            "issues",
            "comments",
            "links",
            "transitions",
            "worklog",
            "changelog",
            "checklists",
            "attachments",
            "remotelinks",
        ],
    ),
    ("Agile boards", ["boards", "sprints", "columns"]),
    ("Dictionaries", ["priorities", "statuses", "resolutions", "issuetypes", "linktypes"]),
    ("Fields, queues & structure", ["fields", "localfields", "components", "queues"]),
    ("Automation & bulk", ["macros", "triggers", "autoactions", "dashboards", "bulk", "import_"]),
    ("Entities, users & search", ["entities", "users", "applications", "filters", "me"]),
]
WIKI_CATEGORIES: list[tuple[str, list[str]]] = [
    ("Pages", ["pages", "resources", "recovery"]),
    ("Collaboration", ["comments", "attachments"]),
    ("Grids (dynamic tables)", ["grids"]),
    ("Async & uploads", ["operations", "uploadsessions"]),
    ("Identity", ["me"]),
]
FORMS_CATEGORIES: list[tuple[str, list[str]]] = [
    ("Surveys & questions", ["surveys", "questions"]),
    ("Responses & export", ["answers", "operations"]),
    ("Distribution", ["keysets", "filling"]),
    ("Media", ["files", "images"]),
    ("Identity", ["me"]),
]


@dataclass(frozen=True)
class DomainSpec:
    """One domain to document: its heading, CLI/MCP namespace slug, live client, and groups."""

    title: str
    slug: str
    client: object
    categories: list[tuple[str, list[str]]]


@dataclass(frozen=True)
class ResourceRow:
    """A single table row: a resource, its wrapped ops, and per-surface reachability.

    ``resource_url`` links the resource name (``None`` → plain text). ``operation_urls`` is
    the final link target per operation — its own endpoint page, else the resource page as a
    fallback, else ``None`` (plain text). ``operation_specific[i]`` is ``True`` when operation
    ``i`` had a dedicated page (vs. falling back to the resource link); it drives the gap stats.
    """

    display: str
    operations: tuple[str, ...]
    has_cli: bool
    has_mcp: bool
    resource_url: str | None
    operation_urls: tuple[str | None, ...]
    operation_specific: tuple[bool, ...]


@dataclass(frozen=True)
class DomainReport:
    """A rendered domain: its category groups (each a list of rows) plus headline totals."""

    title: str
    slug: str
    groups: list[tuple[str, list[ResourceRow]]]
    resource_count: int
    operation_count: int
    mcp_tool_count: int


@dataclass(frozen=True)
class LinkStats:
    """How the doc-link map covers the tables, and which items have no public link at all.

    ``gaps`` lists the ``<domain>.<resource>[.<operation>]`` identifiers rendered as plain text
    (no known URL) so the shortfall is explicit, not silent.
    """

    resources: int
    linked_resources: int
    operations: int
    specific_ops: int
    fallback_ops: int
    plain_ops: int
    gaps: tuple[str, ...]


def _cli_paths() -> list[str]:
    """Every CLI command path (space-joined), via the shared surface enumerator."""
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from tests.snapshots._surface import cli_tree

    return cli_tree()


def _mcp_tool_names() -> list[str]:
    """Every MCP tool name, from the committed snapshot."""
    return MCP_TOOLS.read_text(encoding="utf-8").split()


def _display_name(attribute: str) -> str:
    """Resource attribute → its CLI/MCP/display name (``import_`` → ``import``)."""
    return attribute[:-1] if attribute.endswith("_") else attribute


def _sdk_operations(resource: object) -> tuple[str, ...]:
    """Public op names defined on the resource client class itself, in source order.

    Both hand-written methods (plain functions) and uplink-decorated endpoints
    (``ConsumerMethod`` descriptors) count; dunder and leading-underscore internals do not.
    """
    ops: list[str] = []
    for name, member in type(resource).__dict__.items():
        if name.startswith("_"):
            continue
        if inspect.isfunction(member) or isinstance(member, uplink.builder.ConsumerMethod):
            ops.append(name)
    return tuple(ops)


def _cli_ops(slug: str, display: str, paths: list[str]) -> list[str]:
    """CLI sub-command remainders under ``<slug> <display>`` (segment-exact prefix match)."""
    prefix = [slug, display]
    return [" ".join(s[2:]) for path in paths if (s := path.split())[:2] == prefix and len(s) > 2]


def _mcp_tools(slug: str, display: str, tools: list[str]) -> list[str]:
    """MCP tool names under the ``<slug>_<display>_`` namespace."""
    prefix = f"{slug}_{display}_"
    return [tool for tool in tools if tool.startswith(prefix)]


def _load_link_map() -> dict[str, dict[str, dict]]:
    """The committed doc-link map, keyed ``domain → resource → {resource, operations}``."""
    return tomllib.loads(COVERAGE_URLS.read_text(encoding="utf-8"))


def _doc_url(slug: str, path: str) -> str:
    """A relative api-ref ``path`` → its absolute public Yandex documentation URL."""
    return API_DOCS.format(domain=slug, path=path)


def _link(text: str, url: str | None) -> str:
    """``text`` as a Markdown link to ``url``, or bare ``text`` when there is no URL."""
    return f"[{text}]({url})" if url else text


def _make_row(
    slug: str,
    display: str,
    resource: object,
    urls: dict[str, dict],
    paths: list[str],
    tools: list[str],
) -> ResourceRow:
    """Assemble one :class:`ResourceRow`, resolving each op to its page / resource / plain text."""
    operations = _sdk_operations(resource)
    entry = urls.get(display, {})
    resource_path = entry.get("resource")
    operation_paths = entry.get("operations", {})
    operation_urls: list[str | None] = []
    operation_specific: list[bool] = []
    for operation in operations:
        own = operation_paths.get(operation)
        operation_specific.append(own is not None)
        target = own or resource_path
        operation_urls.append(_doc_url(slug, target) if target else None)
    return ResourceRow(
        display=display,
        operations=operations,
        has_cli=bool(_cli_ops(slug, display, paths)),
        has_mcp=bool(_mcp_tools(slug, display, tools)),
        resource_url=_doc_url(slug, resource_path) if resource_path else None,
        operation_urls=tuple(operation_urls),
        operation_specific=tuple(operation_specific),
    )


def _report(
    spec: DomainSpec, paths: list[str], tools: list[str], urls: dict[str, dict]
) -> DomainReport:
    """Build a fully-computed :class:`DomainReport` from a live client + surface + link data."""
    discovered = {
        name for name, value in vars(spec.client).items() if isinstance(value, BaseYandex)
    }
    placed: set[str] = set()
    groups: list[tuple[str, list[ResourceRow]]] = []
    operation_count = 0

    for heading, attributes in spec.categories:
        rows: list[ResourceRow] = []
        for attribute in attributes:
            resource = getattr(spec.client, attribute)
            if not isinstance(resource, BaseYandex):
                raise SystemExit(f"gen_coverage: {spec.slug}.{attribute} is not a resource client")
            placed.add(attribute)
            display = _display_name(attribute)
            row = _make_row(spec.slug, display, resource, urls, paths, tools)
            if not row.operations:
                raise SystemExit(f"gen_coverage: {spec.slug}.{attribute} exposes no SDK operations")
            operation_count += len(row.operations)
            rows.append(row)
        groups.append((heading, rows))

    unplaced = sorted(discovered - placed)
    if unplaced:
        rows = []
        for attribute in unplaced:
            resource = getattr(spec.client, attribute)
            row = _make_row(spec.slug, _display_name(attribute), resource, urls, paths, tools)
            operation_count += len(row.operations)
            rows.append(row)
        groups.append(("Other", rows))

    return DomainReport(
        title=spec.title,
        slug=spec.slug,
        groups=groups,
        resource_count=len(discovered),
        operation_count=operation_count,
        mcp_tool_count=sum(1 for tool in tools if tool.startswith(f"{spec.slug}_")),
    )


def link_stats(reports: list[DomainReport]) -> LinkStats:
    """Aggregate doc-link coverage across ``reports`` (own page vs. resource fallback vs. none)."""
    resources = linked_resources = 0
    operations = specific = fallback = plain = 0
    gaps: list[str] = []
    for report in reports:
        for _heading, rows in report.groups:
            for row in rows:
                resources += 1
                identifier = f"{report.slug}.{row.display}"
                if row.resource_url:
                    linked_resources += 1
                else:
                    gaps.append(identifier)
                for operation, url, own in zip(
                    row.operations, row.operation_urls, row.operation_specific, strict=True
                ):
                    operations += 1
                    if own:
                        specific += 1
                    elif url:
                        fallback += 1
                    else:
                        plain += 1
                        gaps.append(f"{identifier}.{operation}")
    return LinkStats(
        resources=resources,
        linked_resources=linked_resources,
        operations=operations,
        specific_ops=specific,
        fallback_ops=fallback,
        plain_ops=plain,
        gaps=tuple(sorted(gaps)),
    )


def _render_table(rows: list[ResourceRow]) -> list[str]:
    """The Markdown lines for one resource-group table."""
    lines = [
        "| Resource | Operations | SDK | CLI | MCP |",
        "|----------|------------|:---:|:---:|:---:|",
    ]
    for row in rows:
        cells = zip(row.operations, row.operation_urls, strict=True)
        operations = " · ".join(_link(operation, url) for operation, url in cells)
        cli = YES if row.has_cli else NO
        mcp = YES if row.has_mcp else NO
        lines.append(
            f"| {_link(row.display, row.resource_url)} | {operations} | {YES} | {cli} | {mcp} |"
        )
    return lines


def _render(reports: list[DomainReport]) -> str:
    """The full inner Markdown block (without the surrounding markers)."""
    resources = sum(report.resource_count for report in reports)
    operations = sum(report.operation_count for report in reports)
    # The per-domain tables cover the three service domains, so their MCP counts sum to the
    # domain-scoped `<slug>_…` tools only. The registered MCP surface also includes
    # cross-cutting tools (e.g. `status`) that belong to no single domain; advertise the true
    # total so the summary matches the server's registered tool count.
    domain_mcp_tools = sum(report.mcp_tool_count for report in reports)
    domain_prefixes = tuple(f"{report.slug}_" for report in reports)
    cross_cutting_tools = [
        tool for tool in _mcp_tool_names() if not tool.startswith(domain_prefixes)
    ]
    total_mcp_tools = domain_mcp_tools + len(cross_cutting_tools)
    cross_cutting_names = ", ".join(
        f"`{name}`" for name in sorted({tool.split("_", 1)[0] for tool in cross_cutting_tools})
    )
    stats = link_stats(reports)

    lines = [
        "## Coverage",
        "",
        f"`ycli` wraps **{operations} operations across {resources} resources** of the Tracker, "
        f"Wiki, and Forms REST API — every one reachable from the **Python SDK** and the "
        f"**CLI**, plus {total_mcp_tools} **MCP** tools ({domain_mcp_tools} domain-scoped + "
        f"{len(cross_cutting_tools)} cross-cutting: {cross_cutting_names}) for agents.",
        "",
        "> **Legend** — operations ship on **SDK + CLI**, and the **MCP** server mirrors them "
        "with honest annotations: reads carry `readOnlyHint`, writes carry explicit "
        "destructive/idempotent hints, and `ycli mcp start --read-only` serves the reads-only "
        "view. In each table **SDK** and **CLI** mean the operation is wrapped on that "
        f"surface; **MCP** is {YES} when the resource exposes at least one MCP tool. Resource "
        "and operation names link to the official **Yandex API reference** "
        "(`yandex.ru/support/…/api-ref`). These tables are generated from the code by "
        "[`scripts/gen_coverage.py`](scripts/gen_coverage.py) — do not edit by hand.",
    ]
    for report in reports:
        lines += [
            "",
            f"### {report.title}",
            "",
            f"**{report.resource_count} resources · {report.operation_count} operations · "
            f"{report.mcp_tool_count} MCP tools**",
        ]
        for heading, rows in report.groups:
            lines += ["", f"#### {heading}", "", *_render_table(rows)]

    gaps = ", ".join(f"`{gap}`" for gap in stats.gaps)
    unlinked = (
        f" No public API reference exists yet for {gaps}, shown as plain text."
        if stats.gaps
        else ""
    )
    lines += [
        "",
        f"Every resource and operation above deep-links to the Yandex API reference: "
        f"{stats.specific_ops} of {stats.operations} operations resolve to their own endpoint "
        f"page and {stats.fallback_ops} to their resource's page.{unlinked} "
        "See `CONTRIBUTING.md` for the intentional exclusions (UI-only endpoints with no public "
        "REST API) and per-method notes.",
    ]
    return "\n".join(lines)


def _reports() -> list[DomainReport]:
    """The three per-domain reports, computed from the live clients + committed link map."""
    paths = _cli_paths()
    tools = _mcp_tool_names()
    link_map = _load_link_map()
    specs = [
        DomainSpec(
            "Tracker",
            "tracker",
            TrackerClient(oauth_token="x", organization_id="x"),
            TRACKER_CATEGORIES,
        ),
        DomainSpec(
            "Wiki", "wiki", WikiClient(oauth_token="x", organization_id="x"), WIKI_CATEGORIES
        ),
        DomainSpec(
            "Forms", "forms", FormsClient(oauth_token="x", organization_id="x"), FORMS_CATEGORIES
        ),
    ]
    return [_report(spec, paths, tools, link_map.get(spec.slug, {})) for spec in specs]


def build_block() -> str:
    """The complete marker-wrapped Coverage block that README embeds."""
    return f"{START}\n{_render(_reports())}\n{END}"


def splice(text: str, block: str) -> str:
    """Return ``text`` with its Coverage block replaced by ``block``.

    If the markers already exist, replace between them; otherwise (first run) replace the
    legacy ``## What's covered`` section that sits just before ``## Configure``.
    """
    if START in text and END in text:
        return text[: text.index(START)] + block + text[text.index(END) + len(END) :]
    pattern = re.compile(r"## What's covered.*?(?=\n## Configure)", re.DOTALL)
    if not pattern.search(text):
        raise SystemExit("gen_coverage: could not locate the coverage section to replace")
    return pattern.sub(lambda _match: block + "\n", text)


def main(argv: list[str] | None = None) -> int:
    """CLI entry point; see the module docstring for the three modes."""
    parser = argparse.ArgumentParser(description="Generate README's Coverage section.")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true", help="splice the block into README.md")
    group.add_argument("--check", action="store_true", help="exit 1 if README's block is stale")
    args = parser.parse_args(argv)

    reports = _reports()
    block = f"{START}\n{_render(reports)}\n{END}"
    if args.write:
        README.write_text(splice(README.read_text(encoding="utf-8"), block), encoding="utf-8")
        return 0
    if args.check:
        stats = link_stats(reports)
        print(
            f"gen_coverage links: {stats.specific_ops}/{stats.operations} operations → their own "
            f"page, {stats.fallback_ops} → resource page, {stats.plain_ops} plain-text; "
            f"{stats.linked_resources}/{stats.resources} resources linked. "
            f"Gaps (no public link): {', '.join(stats.gaps) or 'none'}.",
            file=sys.stderr,
        )
        current = README.read_text(encoding="utf-8")
        if current != splice(current, block):
            print(
                "README coverage block is stale; run: uv run python scripts/gen_coverage.py "
                "--write",
                file=sys.stderr,
            )
            return 1
        return 0
    print(block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
