"""Generate the reference pages of the documentation site from the code.

The CLI pages come from Typer's own Markdown generator, the MCP pages from the tools the server
lists, and the SDK pages are mkdocstrings directives that the site build fills from the
docstrings. Each surface gets one page per service, so no page grows to thousands of lines.

Usage::

    uv run scripts/gen_reference.py            # write the pages under docs/en/reference/
    uv run scripts/gen_reference.py --check    # exit 1 if a committed page is stale

``tests/test_docs_site.py`` runs the check, so the reference never drifts from the code.
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path
from typing import Any

import typer
import typer.main
from typer.cli import get_docs_for_click
from typer.core import TyperGroup

from ycli.cli.app import app
from ycli.mcp.selection import Selection
from ycli.mcp.server import build_server
from ycli.yandex.core.resource import Resource
from ycli.yandex.registry import SERVICES

ROOT = Path(__file__).resolve().parent.parent
REFERENCE = ROOT / "docs" / "en" / "reference"
HEADER = "<!-- Generated by scripts/gen_reference.py; do not edit by hand. -->"
FRONT_MATTER = "---\ntype: reference\n---\n"


def _page(body: str) -> str:
    return f"{FRONT_MATTER}\n{HEADER}\n\n{body.strip()}\n"


def cli_pages() -> dict[str, str]:
    """``reference/cli/<command>.md`` for every top-level command, plus the root options."""
    root = typer.main.get_group(app)
    ctx = typer.Context(root, info_name="ycli")
    names = root.list_commands(ctx)
    # The root alone: its options, without recursing into every command; a list links them.
    shallow = TyperGroup(name="ycli", params=root.params, help=root.help, epilog=root.epilog)
    commands = "\n".join(
        f"* [`ycli {name}`]({name}.md): {command.get_short_help_str(80)}"
        for name in names
        if (command := root.get_command(ctx, name)) is not None
    )
    pages = {
        "cli/index.md": _page(
            get_docs_for_click(obj=shallow, ctx=ctx, name="ycli", title="CLI").strip()
            + f"\n\n**Commands**:\n\n{commands}"
        )
    }
    for name in names:
        command = root.get_command(ctx, name)
        assert command is not None
        docs = get_docs_for_click(obj=command, ctx=ctx, name=f"ycli {name}")
        pages[f"cli/{name}.md"] = _page(docs)
    return pages


def _schema_type(schema: dict[str, Any]) -> str:
    """A JSON schema's type in a few words: ``integer``, ``string or null``, ``BoardCreate``."""
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " or ".join(_schema_type(option) for option in schema["anyOf"])
    if schema.get("type") == "array":
        return f"array of {_schema_type(schema.get('items', {}))}"
    if "enum" in schema:
        return " · ".join(f"`{value}`" for value in schema["enum"])
    return str(schema.get("type", "any"))


def _effect(annotations: Any) -> str:
    if annotations.read_only_hint:
        return "read-only"
    if annotations.destructive_hint:
        return "destructive write"
    return "idempotent write" if annotations.idempotent_hint else "write"


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _tool_section(tool: Any) -> list[str]:
    lines = [
        f"## `{tool.name}`",
        "",
        f"*{tool.annotations.title}* · {_effect(tool.annotations)}",
        "",
        (tool.description or "").strip(),
    ]
    properties = tool.parameters.get("properties", {})
    if properties:
        required = set(tool.parameters.get("required", []))
        lines += ["", "| Parameter | Type | Required | Description |", "|---|---|:---:|---|"]
        lines += [
            f"| `{name}` | {_cell(_schema_type(schema))} | {'yes' if name in required else ''}"
            f" | {_cell(str(schema.get('description', '')))} |"
            for name, schema in properties.items()
        ]
    return [*lines, ""]


def mcp_pages() -> dict[str, str]:
    """``reference/mcp/<service>.md``: every tool's hints, description and parameters."""
    server = build_server(Selection())
    tools = asyncio.run(server.list_tools())
    names = [service.name for service in SERVICES]
    pages: dict[str, str] = {}
    for name in names:
        own = [tool for tool in tools if tool.name.startswith(f"{name}_")]
        body = [f"# {name.capitalize()} MCP tools", "", f"{len(own)} tools.", ""]
        for tool in own:
            body += _tool_section(tool)
        pages[f"mcp/{name}.md"] = _page("\n".join(body))
    other = [tool for tool in tools if not tool.name.startswith(tuple(f"{n}_" for n in names))]
    body = ["# Other MCP tools", "", "Tools that belong to no single service.", ""]
    for tool in other:
        body += _tool_section(tool)
    pages["mcp/other.md"] = _page("\n".join(body))
    return pages


def sdk_pages() -> dict[str, str]:
    """``reference/sdk/<service>.md``: the domain client, then each resource's client."""
    pages: dict[str, str] = {}
    for service in SERVICES:
        client_class = service.client_class()
        client = client_class(oauth_token="token", organization_id="org")
        resources = {
            attribute: type(value)
            for attribute, value in vars(client).items()
            if isinstance(value, Resource)
        }
        client.close()
        body = [
            f"# {service.name.capitalize()} SDK",
            "",
            f"Examples use a client built as `{service.name} = {client_class.__name__}"
            '(oauth_token="…", organization_id="…")`.',
            "",
            f"::: {client_class.__module__}.{client_class.__qualname__}",
            "",
        ]
        for attribute, resource_class in resources.items():
            body += [
                f"## {attribute.rstrip('_')}",
                "",
                f"::: {resource_class.__module__}.{resource_class.__qualname__}",
                "",
            ]
        pages[f"sdk/{service.name}.md"] = _page("\n".join(body))
    return pages


def build() -> dict[Path, str]:
    """Every generated page, keyed by its path."""
    pages = {**cli_pages(), **mcp_pages(), **sdk_pages()}
    return {REFERENCE / relative: text for relative, text in pages.items()}


def main(argv: list[str] | None = None) -> int:
    """Write the pages, or with ``--check`` report the stale ones and exit 1."""
    parser = argparse.ArgumentParser(description="Generate the reference pages of the site.")
    parser.add_argument("--check", action="store_true", help="exit 1 if a page is stale")
    args = parser.parse_args(argv)
    pages = build()
    generated_dirs = {path.parent for path in pages}
    orphans = [
        path for directory in generated_dirs for path in directory.glob("*.md") if path not in pages
    ]
    if args.check:
        stale = [
            path
            for path, text in pages.items()
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        for path in [*stale, *orphans]:
            print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
        if stale or orphans:
            print("run: uv run scripts/gen_reference.py", file=sys.stderr)
            return 1
        return 0
    for path in orphans:
        path.unlink()
    for path, text in pages.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
