"""Generate the models of every DataLens schema from the specification DataLens publishes.

DataLens describes its API in one OpenAPI document (about 600 schemas), and its objects are
too large to write by hand: a chart's configuration alone is hundreds of classes. The models
are therefore generated, one module per section of the API, into
``src/ycli/yandex/datalens/schemas/``. A resource's ``models.py`` gives the ones it uses their
public names; nothing else imports from the generated layer.

The pipeline has two steps of ycli's own around ``datamodel-code-generator``:

1. :func:`prepare` rewrites the specification so that the generator's output follows ycli's
   rules (docs/conventions/resources.md): a reply is read as it comes, a set of values is open,
   only the envelope of a request refuses an unknown field, every schema has a name and a
   module.
2. :func:`finish` gives a request envelope the ``RequestBody`` base and each file its header.

Then ruff formats the result as it formats the rest of the package.

Usage::

    uv run scripts/gen_datalens_models.py                  # fetch the specification, write
    uv run scripts/gen_datalens_models.py --spec file.json # ... from a saved copy
    uv run scripts/gen_datalens_models.py --check          # exit 1 if a file was edited by hand
    uv run scripts/gen_datalens_models.py --check --live   # exit 1 if DataLens changed

The specification is not committed (it is DataLens's, and not ours to republish). ``--check``
alone therefore reads no specification: it proves that the committed files are what the last
step leaves, and ``tests/tooling/test_gen_datalens_models.py`` runs it. ``--check --live``
regenerates from the published document; the weekly ``api-drift`` workflow runs it.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Iterator

ROOT = Path(__file__).resolve().parent.parent
SCHEMAS = ROOT / "src" / "ycli" / "yandex" / "datalens" / "schemas"
_HOME = SCHEMAS
SPEC_URL = "https://api.datalens.tech/json/"
HEADER = (
    "# Generated from the DataLens specification by scripts/gen_datalens_models.py;"
    " do not edit by hand.\n"
)
SHARED = "shared"
_REF = "#/components/schemas/"
_GENERATOR_HEADER = re.compile(r"\A# generated by datamodel-codegen:\n(#.*\n)*")
_CLOSED_MODEL = re.compile(
    r"^class (\w+)\(APIModel\):\n"
    r"    model_config = ConfigDict\(\n        extra=\"forbid\",\n    \)\n",
    re.MULTILINE,
)
_MODELS_IMPORT = "from ycli.yandex.models import APIModel\n"


def _snake(name: str) -> str:
    """``WorkbookExport`` -> ``workbook_export``."""
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name).lower()


def _walk(node: Any) -> Iterator[dict[str, Any]]:
    """Every mapping inside ``node``, itself included, parents first."""
    if isinstance(node, dict):
        yield node
        for value in node.values():
            yield from _walk(value)
    elif isinstance(node, list):
        for item in node:
            yield from _walk(item)


def _references(node: Any) -> list[str]:
    """The names of the component schemas ``node`` refers to."""
    return [
        found["$ref"][len(_REF) :]
        for found in _walk(node)
        if isinstance(found.get("$ref"), str) and found["$ref"].startswith(_REF)
    ]


def _union_members(schema: dict[str, Any]) -> list[dict[str, Any]]:
    return [*schema.get("oneOf", []), *schema.get("anyOf", [])]


def _require_discriminators(spec: dict[str, Any]) -> set[int]:
    """Make each union's discriminator a required property of its members; return those nodes.

    pydantic builds a discriminated union only from members that always carry the tag, and
    DataLens leaves it optional in most of them.
    """
    schemas = spec["components"]["schemas"]
    tags: set[int] = set()
    for union in _walk(spec):
        discriminator = union.get("discriminator")
        if not isinstance(discriminator, dict):
            continue
        name = discriminator["propertyName"]
        for member in _union_members(union):
            ref = member.get("$ref", "")
            aimed = schemas.get(ref[len(_REF) :]) if ref.startswith(_REF) else member
            if aimed is None or name not in aimed.get("properties", {}):
                continue
            tags.add(id(aimed["properties"][name]))
            if name not in aimed.get("required", []):
                aimed.setdefault("required", []).append(name)
    return tags


def _open_value_sets(spec: dict[str, Any], keep: set[int]) -> None:
    """A closed set of several string values also takes any string, except a union's tag.

    The API adds values without notice, and a reply with a new one must still parse
    (conventions, "A field with a set of values"). A single value is a tag, not a set.
    """
    for node in list(_walk(spec)):
        values = node.get("enum")
        if (
            isinstance(values, list)
            and len(values) > 1
            and all(isinstance(value, str) for value in values)
            and id(node) not in keep
        ):
            closed = {key: node.pop(key) for key in ("enum", "type") if key in node}
            node["anyOf"] = [closed, {"type": "string"}]


def _name_inline_bodies(spec: dict[str, Any]) -> list[str]:
    """Give each operation's inline request or reply schema a name; return the request names.

    Only the envelope of a request refuses an unknown field: the server does, and a field
    mistyped in an argument should fail before it is sent. Everything else is read as it comes.
    """
    schemas = spec["components"]["schemas"]
    for node in _walk(spec):
        if node.get("additionalProperties") is False:
            del node["additionalProperties"]
    requests = []
    for path, item in spec["paths"].items():
        operation = item["post"]
        name = path.rsplit("/", 1)[1]
        pascal = name[0].upper() + name[1:]
        body = operation.get("requestBody", {}).get("content", {}).get("application/json")
        reply = operation["responses"]["200"].get("content", {}).get("application/json")
        for holder, suffix in ((body, "Request"), (reply, "Response")):
            if not holder or not holder.get("schema"):
                continue  # no body, or `{}`: an untyped reply stays untyped
            if "$ref" not in holder["schema"]:
                if pascal + suffix in schemas:
                    raise SystemExit(f"the specification already has a schema {pascal + suffix}")
                schemas[pascal + suffix] = holder["schema"]
                holder["schema"] = {"$ref": _REF + pascal + suffix}
            if suffix == "Request":
                envelope = holder["schema"]["$ref"][len(_REF) :]
                requests.append(envelope)
                if "properties" in schemas[envelope]:
                    schemas[envelope]["additionalProperties"] = False
    return requests


def _sections(spec: dict[str, Any]) -> dict[str, str]:
    """The module of each schema: the one section whose operations reach it, else ``shared``."""
    schemas = spec["components"]["schemas"]
    reached: dict[str, set[str]] = {name: set() for name in schemas}
    for item in spec["paths"].values():
        operation = item["post"]
        (tag,) = operation["tags"]
        seen: set[str] = set()
        pending = _references(operation)
        while pending:
            name = pending.pop()
            if name not in seen:
                seen.add(name)
                pending += _references(schemas[name])
        for name in seen:
            reached[name].add(tag)
    return {
        name: _snake(next(iter(tags))) if len(tags) == 1 else SHARED
        for name, tags in reached.items()
    }


def prepare(spec: dict[str, Any]) -> dict[str, Any]:
    """The specification rewritten so that the generated models follow ycli's rules.

    Args:
        spec: The OpenAPI document as DataLens publishes it.

    Returns:
        A copy in which a union's discriminator is required in its members, a set of string
        values is open, only a request envelope is closed to unknown fields, every request and
        reply schema has a name, and each schema is named ``<section>.<Name>``.

    Examples:
        >>> spec = {
        ...     "components": {"schemas": {"Mode": {"type": "string", "enum": ["a", "b"]}}},
        ...     "paths": {
        ...         "/rpc/getX": {
        ...             "post": {
        ...                 "tags": ["Things"],
        ...                 "responses": {
        ...                     "200": {
        ...                         "content": {
        ...                             "application/json": {
        ...                                 "schema": {"$ref": "#/components/schemas/Mode"}
        ...                             }
        ...                         }
        ...                     }
        ...                 },
        ...             }
        ...         }
        ...     },
        ... }
        >>> prepare(spec)["components"]["schemas"]
        {'things.Mode': {'anyOf': [{'enum': ['a', 'b'], 'type': 'string'}, {'type': 'string'}]}}
    """
    spec = copy.deepcopy(spec)
    schemas = spec["components"]["schemas"]
    _open_value_sets(spec, keep=_require_discriminators(spec))
    _name_inline_bodies(spec)
    section = _sections(spec)
    for node in _walk(spec):
        ref = node.get("$ref")
        if isinstance(ref, str) and ref.startswith(_REF):
            name = ref[len(_REF) :]
            node["$ref"] = f"{_REF}{section[name]}.{name}"
        mapping = node.get("mapping")
        if isinstance(mapping, dict) and "propertyName" in node:
            node["mapping"] = {
                tag: f"{_REF}{section[ref[len(_REF) :]]}.{ref[len(_REF) :]}"
                if ref.startswith(_REF)
                else ref
                for tag, ref in mapping.items()
            }
    spec["components"]["schemas"] = {
        f"{section[name]}.{name}": schema for name, schema in schemas.items()
    }
    return spec


def finish(text: str) -> str:
    """One generated module as it is committed, before formatting: header and request bases.

    A model the generator closed to unknown fields is the envelope of a request (``prepare``
    closes nothing else), so it takes ``RequestBody``, which is closed already. Running it on
    its own result changes nothing.

    Args:
        text: The module as the generator wrote it, or as this function left it.

    Returns:
        The module with ycli's header and with ``RequestBody`` for the request envelopes.

    Examples:
        >>> module = '''# generated by datamodel-codegen:
        ... #   filename:  spec.json
        ... from ycli.yandex.models import APIModel
        ... class GetArgs(APIModel):
        ...     model_config = ConfigDict(
        ...         extra="forbid",
        ...     )
        ...     dashboard_id: str
        ... '''
        >>> print(finish(module).split("by hand.")[1])
        <BLANKLINE>
        from ycli.yandex.models import APIModel, RequestBody
        class GetArgs(RequestBody):
            dashboard_id: str
        <BLANKLINE>
        >>> finish(finish(module)) == finish(module)
        True
    """
    text = _GENERATOR_HEADER.sub("", text)
    if not text.startswith(HEADER):
        text = HEADER + text
    text, closed = _CLOSED_MODEL.subn(r"class \1(RequestBody):\n", text)
    if closed:
        text = text.replace(
            _MODELS_IMPORT, "from ycli.yandex.models import APIModel, RequestBody\n"
        )
    return text


def _ruff(text: str, name: str) -> str:
    """``text`` as ruff leaves the generated module ``name``: safe fixes, then the formatter.

    The file is named by its committed path, so the settings of that path apply wherever the
    text is being written.
    """
    path = _HOME / name
    for arguments in (["check", "--fix-only", "--quiet"], ["format", "--quiet"]):
        text = subprocess.run(
            [sys.executable, "-m", "ruff", *arguments, "--stdin-filename", str(path), "-"],
            input=text,
            capture_output=True,
            text=True,
            check=True,
            cwd=ROOT,
        ).stdout
    return text


def generate(spec: dict[str, Any]) -> dict[Path, str]:
    """Every module of the generated layer for ``spec``, by the path it is committed at."""
    with tempfile.TemporaryDirectory() as scratch:
        source = Path(scratch) / "spec.json"
        source.write_text(json.dumps(prepare(spec)), encoding="utf-8")
        output = Path(scratch) / "schemas"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                *("--input", str(source), "--input-file-type", "openapi"),
                *("--output", str(output), "--output-model-type", "pydantic_v2.BaseModel"),
                *("--target-python-version", "3.12", "--formatters", "builtin"),
                *("--base-class", "ycli.yandex.models.APIModel", "--openapi-scopes", "schemas"),
                *("--enum-field-as-literal", "all", "--treat-dot-as-module"),
                "--use-union-operator",
                "--use-standard-collections",
                "--use-double-quotes",
                "--use-default-kwarg",
                "--use-schema-description",
                "--snake-case-field",
                "--field-constraints",
                "--disable-timestamp",
            ],
            check=True,
            cwd=ROOT,
        )
        return {
            SCHEMAS / path.name: _ruff(finish(path.read_text(encoding="utf-8")), path.name)
            for path in sorted(output.glob("*.py"))
        }


def edited_by_hand() -> list[Path]:
    """Committed modules that are not what the last step of the pipeline leaves."""
    return [
        path
        for path in sorted(SCHEMAS.glob("*.py"))
        if (text := path.read_text(encoding="utf-8")) != _ruff(finish(text), path.name)
        or not text.startswith(HEADER)
    ]


def _published() -> dict[str, Any]:
    import httpx2

    return httpx2.get(SPEC_URL, timeout=60, follow_redirects=True).raise_for_status().json()


def main(argv: list[str] | None = None) -> int:
    """Write the generated layer, or report what a check found and exit 1."""
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--spec", type=Path, help="a saved copy of the specification")
    parser.add_argument("--check", action="store_true", help="exit 1 if a file was edited by hand")
    parser.add_argument("--live", action="store_true", help="with --check: compare with DataLens")
    args = parser.parse_args(argv)
    if args.check and not args.live:
        edited = edited_by_hand()
        for path in edited:
            print(f"edited by hand: {path.name}", file=sys.stderr)
        return 1 if edited else 0
    spec = json.loads(args.spec.read_text(encoding="utf-8")) if args.spec else _published()
    modules = generate(spec)
    stale = [
        path
        for path in {*modules, *SCHEMAS.glob("*.py")}
        if path not in modules
        or not path.exists()
        or path.read_text(encoding="utf-8") != modules[path]
    ]
    if args.check:
        for path in sorted(stale):
            print(f"differs from the published specification: {path.name}")
        return 1 if stale else 0
    SCHEMAS.mkdir(parents=True, exist_ok=True)
    for path in SCHEMAS.glob("*.py"):
        if path not in modules:
            path.unlink()
    for path, text in modules.items():
        path.write_text(text, encoding="utf-8")
    print(f"{len(modules)} modules, {sum(text.count(chr(10)) for text in modules.values())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
