"""Generate the models of every DataLens schema from the specification DataLens publishes.

DataLens describes its API in one OpenAPI document (about 600 schemas), and its objects are
too large to write by hand: a chart's configuration alone is hundreds of classes. The models
are therefore generated, one module per section of the API, into
``src/ycli/yandex/datalens/schemas/``. A resource's ``models.py`` gives the ones it uses their
public names; nothing else imports from the generated layer.

The pipeline has two steps of ycli's own around ``datamodel-code-generator``:

1. :func:`prepare` rewrites the specification so that the generator's output follows ycli's
   rules (docs/conventions/resources.md, "Generated models"): no directive to the generator, no
   default and no limit on a value survives, a reply is read as it comes, a set of values is
   open, only the envelope of a request refuses an unknown field, every object has a name made
   from its place, and each schema an operation reaches has a module.
2. :func:`finish` gives a request envelope the ``RequestBody`` base and each file its header.

Then ruff formats the result as it formats the rest of the package, and :func:`foreign`
refuses any module that is more than plain models: the document is downloaded, and the modules
are imported by every test run.

Usage::

    uv run scripts/gen_datalens_models.py                  # fetch the specification, write
    uv run scripts/gen_datalens_models.py --spec file.json # ... from a saved copy
    uv run scripts/gen_datalens_models.py --check          # exit 1 if a file is not the script's
    uv run scripts/gen_datalens_models.py --check --live   # exit 1 if DataLens changed

The specification is not committed (it is DataLens's, and not ours to republish). ``--check``
alone therefore reads no specification: the script records the checksum of every file it writes
(``scripts/datalens_schemas.sha256``), and the check holds that the committed files are those,
none added and none removed; ``tests/tooling/test_gen_datalens_models.py`` runs it.
``--check --live`` regenerates from the published document; the weekly ``api-drift`` workflow
runs it.
"""

from __future__ import annotations

import argparse
import ast
import copy
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Iterator, Mapping

ROOT = Path(__file__).resolve().parent.parent
SCHEMAS = ROOT / "src" / "ycli" / "yandex" / "datalens" / "schemas"
_HOME = SCHEMAS
MANIFEST = ROOT / "scripts" / "datalens_schemas.sha256"
SPEC_URL = "https://api.datalens.tech/json/"
HEADER = (
    "# Generated from the DataLens specification by scripts/gen_datalens_models.py;"
    " do not edit by hand.\n"
)
SHARED = "shared"
_REF = "#/components/schemas/"
_GENERATOR_HEADER = re.compile(r"\A# generated by datamodel-codegen:\n(#.*\n)*")
_CLOSED_MODEL = re.compile(
    r"^class (\w+)\(APIModel\):\n"
    r"((?:    \"\"\"(?:(?!\"\"\")[\s\S])*\"\"\"\n\n?)?)"
    r"    model_config = ConfigDict\(\n        extra=\"forbid\",\n    \)\n",
    re.MULTILINE,
)
# What a generated module may import, inherit from and call (``foreign``).
_MODULES = {"__future__", "typing", "datetime", "pydantic", "ycli.yandex.models"}
_BASES = {"APIModel", "RequestBody", "RootModel"}
_CALLS = {"Field", "ConfigDict"}
_MODELS_IMPORT = "from ycli.yandex.models import APIModel\n"


def _snake(name: str) -> str:
    """``WorkbookExport`` -> ``workbook_export``."""
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name).lower()


def _pascal(name: str) -> str:
    """``created_by`` -> ``CreatedBy``; ``revId`` -> ``RevId``."""
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^A-Za-z0-9]+", name))


# Where a schema holds other schemas: under a name each, in a list, or as one value.
_NAMED = ("properties", "patternProperties", "$defs")
_LISTED = ("oneOf", "anyOf", "allOf", "prefixItems")
_SINGLE = ("items", "additionalProperties", "not")


def _children(schema: dict[str, Any]) -> Iterator[tuple[str, dict[str, Any], Any, Any]]:
    """The schemas directly inside ``schema``: a name suffix, the child, its holder and key."""
    for keyword in _NAMED:
        for name, child in schema.get(keyword, {}).items():
            if isinstance(child, dict):
                yield _pascal(name), child, schema[keyword], name
    for keyword in _LISTED:
        for index, child in enumerate(schema.get(keyword, [])):
            if isinstance(child, dict):
                yield f"Variant{index + 1}", child, schema[keyword], index
    for keyword, suffix in zip(_SINGLE, ("Item", "Value", "Not"), strict=True):
        if isinstance(schema.get(keyword), dict):
            yield suffix, schema[keyword], schema, keyword


def _schemas(schema: dict[str, Any]) -> Iterator[dict[str, Any]]:
    """``schema`` and every schema inside it; a map of property names is not one."""
    yield schema
    for _, child, _, _ in _children(schema):
        yield from _schemas(child)


def _bodies(spec: dict[str, Any]) -> Iterator[tuple[str, str, str, dict[str, Any]]]:
    """Each operation's request and reply: name, section, ``Request``/``Response``, holder."""
    for path, item in spec["paths"].items():
        operation = item["post"]
        (tag,) = operation["tags"]
        body = operation.get("requestBody", {}).get("content", {}).get("application/json")
        reply = operation["responses"]["200"].get("content", {}).get("application/json")
        for holder, kind in ((body, "Request"), (reply, "Response")):
            if holder and holder.get("schema"):  # no body, or `{}`: untyped stays untyped
                yield path.rsplit("/", 1)[1], tag, kind, holder


def _every_schema(spec: dict[str, Any]) -> Iterator[dict[str, Any]]:
    for schema in spec["components"]["schemas"].values():
        yield from _schemas(schema)
    for _, _, _, holder in _bodies(spec):
        yield from _schemas(holder["schema"])


def _target(spec: dict[str, Any], schema: dict[str, Any]) -> dict[str, Any] | None:
    """The component ``schema`` refers to, or ``schema`` itself when it is written in place."""
    ref = schema.get("$ref")
    if not isinstance(ref, str):
        return schema
    return spec["components"]["schemas"].get(ref.removeprefix(_REF))


# A limit on a value: its length, its range, its pattern, how many items it holds.
_LIMITS = frozenset(
    {
        "minLength",
        "maxLength",
        "pattern",
        "minimum",
        "maximum",
        "exclusiveMinimum",
        "exclusiveMaximum",
        "multipleOf",
        "minItems",
        "maxItems",
        "uniqueItems",
        "minProperties",
        "maxProperties",
    }
)


def _plain(spec: dict[str, Any]) -> None:
    """Drop what must not reach the generated code: directives, defaults and limits.

    A key that begins with ``x-`` or ``custom`` can tell the generator to import a module or to
    inherit from a class of its choosing; the document is downloaded, so none is honoured. A
    ``default`` would be sent with a body whose caller never set the field: what is not given is
    ``None`` and stays out of the request (conventions, "ycli sends what the caller gave"). A
    limit on a value is the API's rule to enforce, and its answer says more than a copy of the
    rule that goes stale (ARCH-9).
    """
    for schema in list(_every_schema(spec)):
        for key in [
            key
            for key in schema
            if key.startswith(("x-", "custom")) or key == "default" or key in _LIMITS
        ]:
            del schema[key]


def _require_discriminators(spec: dict[str, Any]) -> set[int]:
    """Make each union's discriminator a required property of its members; return those nodes.

    pydantic builds a discriminated union only from members that always carry the tag, and
    DataLens leaves it optional in most of them.
    """
    tags: set[int] = set()
    for union in list(_every_schema(spec)):
        discriminator = union.get("discriminator")
        if not isinstance(discriminator, dict):
            continue
        name = discriminator["propertyName"]
        for member in [*union.get("oneOf", []), *union.get("anyOf", [])]:
            aimed = _target(spec, member)
            if aimed is None or name not in aimed.get("properties", {}):
                continue
            tags.add(id(aimed["properties"][name]))
            if name not in aimed.get("required", []):
                aimed.setdefault("required", []).append(name)
    return tags


def _open_value_sets(spec: dict[str, Any], keep: set[int]) -> None:
    """A closed set of several string values also takes any string, except a union's tag.

    The API adds values without notice, and a reply with a new one must still parse
    (conventions, "A field with a set of values"). A single value is a tag, not a set; a set
    that also allows ``null`` is still a set of strings.
    """
    for schema in list(_every_schema(spec)):
        values = schema.get("enum")
        if not isinstance(values, list) or id(schema) in keep:
            continue
        strings = [value for value in values if isinstance(value, str)]
        if len(strings) > 1 and all(value is None for value in values if value not in strings):
            closed = {key: schema.pop(key) for key in ("enum", "type") if key in schema}
            schema["anyOf"] = [closed, {"type": "string"}]


def _close_only_requests(spec: dict[str, Any]) -> None:
    """Only the envelope of a request refuses an unknown field; a reply is read as it comes.

    The server refuses an unknown key of a request, and a field mistyped in an argument should
    fail before it is sent. An envelope the document itself leaves open stays open.
    """
    for schema in list(_every_schema(spec)):
        if schema.get("additionalProperties") is False:
            del schema["additionalProperties"]
    for _, _, kind, holder in _bodies(spec):
        envelope = _target(spec, holder["schema"])
        if kind == "Request" and envelope and "properties" in envelope:
            envelope.setdefault("additionalProperties", False)


def _name_every_object(spec: dict[str, Any]) -> None:
    """Give every object written in place a name of its own, made from where it stands.

    The generator would name it after its property and number the clashes in the order it
    meets them, so a schema added elsewhere would rename classes that did not change. A name
    made from the path (``DashboardDataTabsItem``) moves only when its own parents do.
    """
    schemas = spec["components"]["schemas"]

    def unique(name: str) -> str:
        found, number = name, 1
        while found in schemas:
            number += 1
            found = f"{name}{number}"
        return found

    def descend(schema: dict[str, Any], name: str) -> None:
        for suffix, child, holder, key in list(_children(schema)):
            if "$ref" in child:
                continue
            # A member of ``allOf`` is a part of this object, not an object of its own.
            part = holder is schema.get("allOf")
            if "properties" in child and not part:
                named = unique(name + suffix)
                schemas[named] = child
                holder[key] = {"$ref": _REF + named}
                descend(child, named)
            else:
                descend(child, name if part else name + suffix)

    for name, _, kind, holder in list(_bodies(spec)):
        if "$ref" not in holder["schema"]:
            named = unique(name[:1].upper() + name[1:] + kind)
            schemas[named] = holder["schema"]
            holder["schema"] = {"$ref": _REF + named}
    for name in list(schemas):
        descend(schemas[name], name)


def _references(schema: dict[str, Any]) -> list[str]:
    """The names of the component schemas ``schema`` refers to, at any depth."""
    return [
        found["$ref"].removeprefix(_REF)
        for found in _schemas(schema)
        if isinstance(found.get("$ref"), str)
    ]


def _sections(spec: dict[str, Any]) -> dict[str, str]:
    """The module of each schema an operation reaches: its one section, else ``shared``.

    A schema no operation reaches gets no module: nothing can send or receive it.
    """
    schemas = spec["components"]["schemas"]
    reached: dict[str, set[str]] = {}
    for _, tag, _, holder in _bodies(spec):
        seen: set[str] = set()
        pending = _references(holder["schema"])
        while pending:
            name = pending.pop()
            if name not in seen:
                seen.add(name)
                pending += _references(schemas[name])
        for name in seen:
            reached.setdefault(name, set()).add(tag)
    return {
        name: _snake(next(iter(tags))) if len(tags) == 1 else SHARED
        for name, tags in reached.items()
    }


def prepare(spec: dict[str, Any]) -> dict[str, Any]:
    """The specification rewritten so that the generated models follow ycli's rules.

    Args:
        spec: The OpenAPI document as DataLens publishes it.

    Returns:
        A copy with no generator directives and no defaults, in which a union's discriminator is
        required in its members, a set of string values is open, only a request envelope is
        closed to unknown fields, every object has a name made from its place, a schema no
        operation reaches is gone, and each schema is named ``<section>.<Name>``.

    Raises:
        SystemExit: A name of the document cannot be a module or a class name.

    Examples:
        >>> spec = {
        ...     "components": {"schemas": {"Mode": {"type": "string", "enum": ["a", "b"]}}},
        ...     "paths": {
        ...         "/rpc/getX": {
        ...             "post": {
        ...                 "tags": ["Things"],
        ...                 "responses": {
        ...                     "200": {
        ...                         "content": {
        ...                             "application/json": {
        ...                                 "schema": {"$ref": "#/components/schemas/Mode"}
        ...                             }
        ...                         }
        ...                     }
        ...                 },
        ...             }
        ...         }
        ...     },
        ... }
        >>> prepare(spec)["components"]["schemas"]
        {'things.Mode': {'anyOf': [{'enum': ['a', 'b'], 'type': 'string'}, {'type': 'string'}]}}
    """
    spec = copy.deepcopy(spec)
    _plain(spec)
    _open_value_sets(spec, keep=_require_discriminators(spec))
    _close_only_requests(spec)
    _name_every_object(spec)
    section = _sections(spec)
    schemas = {
        name: schema for name, schema in spec["components"]["schemas"].items() if name in section
    }
    for name in section:
        # One module per section, one class per schema: a dot would make a package of either.
        if not re.fullmatch(r"\w+", name) or not re.fullmatch(r"\w+", section[name]):
            raise SystemExit(f"the specification names a schema or a section {name!r}")

    def moved(ref: str) -> str:
        name = ref.removeprefix(_REF)
        return f"{_REF}{section[name]}.{name}"

    spec["components"]["schemas"] = schemas
    for schema in list(_every_schema(spec)):
        if isinstance(schema.get("$ref"), str):
            schema["$ref"] = moved(schema["$ref"])
        mapping = schema.get("discriminator", {}).get("mapping")
        if isinstance(mapping, dict):
            schema["discriminator"]["mapping"] = {
                tag: moved(ref) if ref.startswith(_REF) else ref for tag, ref in mapping.items()
            }
    spec["components"]["schemas"] = {
        f"{section[name]}.{name}": schema for name, schema in schemas.items()
    }
    return spec


def finish(text: str) -> str:
    """One generated module as it is committed, before formatting: header and request bases.

    A model the generator closed to unknown fields is the envelope of a request (``prepare``
    closes nothing else), so it takes ``RequestBody``, which is closed already. Running it on
    its own result changes nothing.

    Args:
        text: The module as the generator wrote it, or as this function left it.

    Returns:
        The module with ycli's header and with ``RequestBody`` for the request envelopes.

    Examples:
        >>> module = '''# generated by datamodel-codegen:
        ... #   filename:  spec.json
        ... from ycli.yandex.models import APIModel
        ... class GetArgs(APIModel):
        ...     model_config = ConfigDict(
        ...         extra="forbid",
        ...     )
        ...     dashboard_id: str
        ... '''
        >>> print(finish(module).split("by hand.")[1])
        <BLANKLINE>
        from ycli.yandex.models import APIModel, RequestBody
        class GetArgs(RequestBody):
            dashboard_id: str
        <BLANKLINE>
        >>> finish(finish(module)) == finish(module)
        True
    """
    text = _GENERATOR_HEADER.sub("", text)
    if not text.startswith(HEADER):
        text = HEADER + text
    text, closed = _CLOSED_MODEL.subn(r"class \1(RequestBody):\n\2", text)
    if closed:
        text = text.replace(
            _MODELS_IMPORT, "from ycli.yandex.models import APIModel, RequestBody\n"
        )
    return text


def _ruff(text: str, name: str) -> str:
    """``text`` as ruff leaves the generated module ``name``: safe fixes, then the formatter.

    The file is named by its committed path, so the settings of that path apply wherever the
    text is being written.
    """
    path = _HOME / name
    for arguments in (["check", "--fix-only", "--quiet"], ["format", "--quiet"]):
        text = subprocess.run(
            [sys.executable, "-m", "ruff", *arguments, "--stdin-filename", str(path), "-"],
            input=text,
            capture_output=True,
            text=True,
            check=True,
            cwd=ROOT,
        ).stdout
    return text


def foreign(text: str) -> list[str]:
    r"""What in a generated module is not a plain model: the reason it may not be imported.

    The modules are written from a downloaded document and imported by every test run, so each
    must be nothing but imports from a few known modules and classes that declare fields. A
    module that imports anything else, inherits from a class of another package, or runs any
    code but ``Field(...)`` and ``ConfigDict(...)`` is refused.

    Examples:
        >>> foreign("from subprocess import Popen\nclass Chart(Popen):\n    pass\n")
        ['line 1: imports subprocess', 'line 2: Chart inherits from Popen']
        >>> foreign("from pydantic import Field\nclass A(APIModel):\n    x: int = Field(1)\n")
        []
    """
    found = []
    tree = ast.parse(text)
    own = {node.name for node in tree.body if isinstance(node, ast.ClassDef)}
    sections: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.ImportFrom):
            if node.level == 1:  # a sibling module of the generated package, or a class of one
                own |= {alias.asname or alias.name for alias in node.names}
                sections |= {alias.asname or alias.name for alias in node.names}
            elif node.level or node.module not in _MODULES:
                found.append(f"line {node.lineno}: imports {'.' * node.level}{node.module or ''}")
        elif isinstance(node, ast.ClassDef):
            for base in node.bases:
                root = base.value if isinstance(base, ast.Subscript) else base
                named = isinstance(root, ast.Name) and root.id in own | _BASES
                sibling = (
                    isinstance(root, ast.Attribute)
                    and isinstance(root.value, ast.Name)
                    and root.value.id in sections
                )
                if not (named or sibling):
                    found.append(
                        f"line {node.lineno}: {node.name} inherits from {ast.unparse(base)}"
                    )
            found += [
                f"line {item.lineno}: {node.name} holds {type(item).__name__}"
                for item in node.body
                if not isinstance(item, ast.AnnAssign | ast.Assign | ast.Pass)
                and not (isinstance(item, ast.Expr) and isinstance(item.value, ast.Constant))
            ]
            found += [
                f"line {call.lineno}: {node.name} calls {ast.unparse(call.func)}"
                for call in ast.walk(node)
                if isinstance(call, ast.Call) and ast.unparse(call.func) not in _CALLS
            ]
        else:
            found.append(f"line {node.lineno}: a statement that is no import and no class")
    return found


def generate(spec: dict[str, Any]) -> dict[str, str]:
    """Every module of the generated layer for ``spec``, by its file name.

    Raises:
        SystemExit: The generator wrote a package instead of a module, or a module that is not
            a plain model (see :func:`foreign`).
    """
    with tempfile.TemporaryDirectory() as scratch:
        source = Path(scratch) / "spec.json"
        source.write_text(json.dumps(prepare(spec)), encoding="utf-8")
        output = Path(scratch) / "schemas"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                *("--input", str(source), "--input-file-type", "openapi"),
                *("--output", str(output), "--output-model-type", "pydantic_v2.BaseModel"),
                *("--target-python-version", "3.12", "--formatters", "builtin"),
                *("--base-class", "ycli.yandex.models.APIModel", "--openapi-scopes", "schemas"),
                *("--enum-field-as-literal", "all", "--treat-dot-as-module"),
                "--use-union-operator",
                "--use-standard-collections",
                "--use-double-quotes",
                "--use-default-kwarg",
                "--use-schema-description",
                "--snake-case-field",
                "--field-constraints",
                "--disable-timestamp",
            ],
            check=True,
            cwd=ROOT,
        )
        nested = sorted(path.name for path in output.iterdir() if path.is_dir())
        if nested:
            raise SystemExit(f"the generator wrote packages, not modules: {nested}")
        modules = {
            path.name: _ruff(finish(path.read_text(encoding="utf-8")), path.name)
            for path in sorted(output.glob("*.py"))
        }
    refused = [f"{name}: {why}" for name, text in modules.items() for why in foreign(text)]
    if refused:
        raise SystemExit("the generated code is not plain models:\n" + "\n".join(refused))
    return modules


def _digest(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def manifest(modules: Mapping[str, str]) -> str:
    """The record of a generation: one ``<sha256>  <file name>`` line per module."""
    return "".join(f"{_digest(text)}  {name}\n" for name, text in sorted(modules.items()))


def edited_by_hand() -> list[str]:
    """How the committed layer differs from what the script last wrote (empty: it does not).

    The script records every file it writes with its checksum (``MANIFEST``). A file changed,
    added or removed without the script shows here, and so does a file that is not plain
    models. It reads no specification. What it cannot tell: that the record itself was edited
    to match, which a reviewer sees as a change of two files with no change of the script.
    """
    recorded = {}
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        digest, _, name = line.partition("  ")
        recorded[name] = digest
    committed = {
        path.name: path.read_text(encoding="utf-8") for path in sorted(SCHEMAS.glob("*.py"))
    }
    found = [
        f"{name}: recorded, not in the directory"
        for name in sorted(recorded.keys() - committed.keys())
    ]
    for name, text in committed.items():
        if name not in recorded:
            found.append(f"{name}: not written by the script")
        elif _digest(text) != recorded[name]:
            found.append(f"{name}: differs from what the script wrote")
        found += [f"{name}: {why}" for why in foreign(text)]
    found += [
        f"{path.name}: a directory"
        for path in sorted(SCHEMAS.iterdir())
        if path.is_dir() and path.name != "__pycache__"
    ]
    return found


def _published() -> dict[str, Any]:
    import httpx2

    return httpx2.get(SPEC_URL, timeout=60, follow_redirects=True).raise_for_status().json()


def main(argv: list[str] | None = None) -> int:
    """Write the generated layer, or report what a check found and exit 1."""
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--spec", type=Path, help="a saved copy of the specification")
    parser.add_argument("--check", action="store_true", help="exit 1 if a file was edited by hand")
    parser.add_argument("--live", action="store_true", help="with --check: compare with DataLens")
    args = parser.parse_args(argv)
    if args.check and not args.live:
        edited = edited_by_hand()
        for line in edited:
            print(f"not what the script wrote: {line}", file=sys.stderr)
        return 1 if edited else 0
    spec = json.loads(args.spec.read_text(encoding="utf-8")) if args.spec else _published()
    modules = generate(spec)
    committed = {path.name: path.read_text(encoding="utf-8") for path in SCHEMAS.glob("*.py")}
    if args.check:
        stale = sorted(
            name
            for name in modules.keys() | committed.keys()
            if modules.get(name) != committed.get(name)
        )
        for name in stale:
            print(f"differs from the published specification: {name}")
        return 1 if stale else 0
    SCHEMAS.mkdir(parents=True, exist_ok=True)
    for name in committed.keys() - modules.keys():
        (SCHEMAS / name).unlink()
    for name, text in modules.items():
        (SCHEMAS / name).write_text(text, encoding="utf-8")
    MANIFEST.write_text(manifest(modules), encoding="utf-8")
    print(f"{len(modules)} modules, {sum(text.count(chr(10)) for text in modules.values())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
