"""Generate the models of every DataLens schema from the specification DataLens publishes.

DataLens describes its API in one OpenAPI document (about 600 schemas), and its objects are
too large to write by hand: a chart's configuration alone is hundreds of classes. The models
are therefore generated, one module per section of the API, into
``src/ycli/yandex/datalens/schemas/``. A resource's ``models.py`` gives the ones it uses their
public names; nothing else imports from the generated layer.

The pipeline has two steps of ycli's own around ``datamodel-code-generator``:

1. :func:`prepare` rewrites the specification so that the generator's output follows ycli's
   rules (docs/conventions/resources.md, "Generated models"): no directive to the generator, no
   default and no limit on a value survives, a number stays the whole number or the fraction
   it was given as, a reply is read as it comes, no object requires
   a field but the one that tells its kind (the top level of a request keeps the arguments
   of its operation), a set of values is open, only the envelope of a
   request refuses an unknown field, every object has a name made from its place, and each
   schema an operation reaches has a module.
2. :func:`finish` gives a request envelope the ``RequestBody`` base and each file its header.

Then ruff formats the result as it formats the rest of the package, and :func:`foreign`
refuses any module that is more than plain models: the document is downloaded, and the modules
are imported by every test run.

Usage::

    uv run scripts/gen_datalens_models.py                  # fetch the specification, write
    uv run scripts/gen_datalens_models.py --spec file.json # ... from a saved copy
    uv run scripts/gen_datalens_models.py --check          # exit 1 if a file is not the script's
    uv run scripts/gen_datalens_models.py --check --live   # exit 1 if DataLens changed

The specification is not committed (it is DataLens's, and not ours to republish). ``--check``
alone therefore reads no specification: the script records the checksum of every file it writes
(``scripts/datalens_schemas.sha256``), and the check holds that the committed files are those,
none added and none removed; ``tests/tooling/test_gen_datalens_models.py`` runs it.
``--check --live`` regenerates from the published document; the weekly ``api-drift`` workflow
runs it.
"""

from __future__ import annotations

import argparse
import ast
import copy
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Iterator, Mapping

ROOT = Path(__file__).resolve().parent.parent
SCHEMAS = ROOT / "src" / "ycli" / "yandex" / "datalens" / "schemas"
_HOME = SCHEMAS
MANIFEST = ROOT / "scripts" / "datalens_schemas.sha256"
SPEC_URL = "https://api.datalens.tech/json/"
HEADER = (
    "# Generated from the DataLens specification by scripts/gen_datalens_models.py;"
    " do not edit by hand.\n"
)
SHARED = "shared"
# The one class every union of kinds falls back to, and what it says of itself.
SPARE = "OtherKind"
_SPARE_SAYS = "A kind the specification does not describe: kept as it came."
_REF = "#/components/schemas/"
_GENERATOR_HEADER = re.compile(r"\A# generated by datamodel-codegen:\n(#.*\n)*")
_CLOSED_MODEL = re.compile(
    r"^class (\w+)\(APIModel\):\n"
    r"((?:    \"\"\"(?:(?!\"\"\")[\s\S])*\"\"\"\n\n?)?)"
    r"    model_config = ConfigDict\(\n        extra=\"forbid\",\n    \)\n",
    re.MULTILINE,
)
# What a generated module may import, inherit from and call (``foreign``).
_MODULES = {"typing", "datetime", "pydantic", "ycli.yandex.models"}
_BASES = {"APIModel", "RequestBody", "RootModel"}
_CALLS = {"Field", "ConfigDict"}
_MODELS_IMPORT = "from ycli.yandex.models import APIModel\n"


def _snake(name: str) -> str:
    """``WorkbookExport`` -> ``workbook_export``."""
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name).lower()


def _pascal(name: str) -> str:
    """``created_by`` -> ``CreatedBy``; ``revId`` -> ``RevId``."""
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^A-Za-z0-9]+", name))


# Where a schema holds other schemas: under a name each, in a list, or as one value.
_NAMED = ("properties", "patternProperties", "$defs")
_LISTED = ("oneOf", "anyOf", "allOf", "prefixItems")
_SINGLE = ("items", "additionalProperties", "not")


def _children(schema: dict[str, Any]) -> Iterator[tuple[str, dict[str, Any], Any, Any]]:
    """The schemas directly inside ``schema``: a name suffix, the child, its holder and key."""
    for keyword in _NAMED:
        for name, child in schema.get(keyword, {}).items():
            if isinstance(child, dict):
                yield _pascal(name), child, schema[keyword], name
    for keyword in _LISTED:
        for index, child in enumerate(schema.get(keyword, [])):
            if isinstance(child, dict):
                yield f"Variant{index + 1}", child, schema[keyword], index
    for keyword, suffix in zip(_SINGLE, ("Item", "Value", "Not"), strict=True):
        if isinstance(schema.get(keyword), dict):
            yield suffix, schema[keyword], schema, keyword


def _schemas(schema: dict[str, Any]) -> Iterator[dict[str, Any]]:
    """``schema`` and every schema inside it; a map of property names is not one."""
    yield schema
    for _, child, _, _ in _children(schema):
        yield from _schemas(child)


def _bodies(spec: dict[str, Any]) -> Iterator[tuple[str, str, str, dict[str, Any]]]:
    """Each operation's request and reply: name, section, ``Request``/``Response``, holder."""
    for path, item in spec["paths"].items():
        operation = item["post"]
        (tag,) = operation["tags"]
        body = operation.get("requestBody", {}).get("content", {}).get("application/json")
        reply = operation["responses"]["200"].get("content", {}).get("application/json")
        for holder, kind in ((body, "Request"), (reply, "Response")):
            if holder and holder.get("schema"):  # no body, or `{}`: untyped stays untyped
                yield path.rsplit("/", 1)[1], tag, kind, holder


def _every_schema(spec: dict[str, Any]) -> Iterator[dict[str, Any]]:
    for schema in spec["components"]["schemas"].values():
        yield from _schemas(schema)
    for _, _, _, holder in _bodies(spec):
        yield from _schemas(holder["schema"])


def _target(spec: dict[str, Any], schema: dict[str, Any]) -> dict[str, Any] | None:
    """The component ``schema`` refers to, or ``schema`` itself when it is written in place."""
    ref = schema.get("$ref")
    if not isinstance(ref, str):
        return schema
    return spec["components"]["schemas"].get(ref.removeprefix(_REF))


# A limit on a value: its length, its range, its pattern, how many items it holds.
_LIMITS = frozenset(
    {
        "minLength",
        "maxLength",
        "pattern",
        "minimum",
        "maximum",
        "exclusiveMinimum",
        "exclusiveMaximum",
        "multipleOf",
        "minItems",
        "maxItems",
        "uniqueItems",
        "minProperties",
        "maxProperties",
    }
)


def _plain(spec: dict[str, Any]) -> None:
    """Drop what must not reach the generated code: directives, defaults and limits.

    A key that begins with ``x-`` or ``custom`` can tell the generator to import a module or to
    inherit from a class of its choosing; the document is downloaded, so none is honoured. A
    ``default`` would be sent with a body whose caller never set the field: what is not given is
    ``None`` and stays out of the request (conventions, "ycli sends what the caller gave"). A
    limit on a value is the API's rule to enforce, and its answer says more than a copy of the
    rule that goes stale (ARCH-9).
    """
    for schema in list(_every_schema(spec)):
        for key in [
            key
            for key in schema
            if key.startswith(("x-", "custom")) or key == "default" or key in _LIMITS
        ]:
            del schema[key]


# A value the document marks ``writeOnly`` is sent and never read back: a password, a token.
# Two names it leaves unmarked hold credentials all the same, and two it marks hold none (#388).
_SECRET_MAPS = {
    "secret_headers": "the headers of an API connection that carry its credentials",
    "extra_credentials": "the credentials a connection passes on to its source",
}
_NOT_SECRETS = {
    "dir_path": "the folder a connection is created in: a path, shown wherever it is read",
    "ssl_ca": "a certificate authority's certificate: public by its nature",
}


def _type_secrets(spec: dict[str, Any]) -> int:
    """Give every secret of the document the type of one; return how many fields got it.

    A string the document marks ``writeOnly`` becomes a ``password`` string, which the
    generator writes as ``SecretStr``: its value is masked wherever the model is printed
    (``repr``, an error, a command's output) and goes out as it is only in a request
    (``ycli.yandex.models.APIModel``). The values of a map of ``_SECRET_MAPS`` are secrets
    the same way; the names in it are not. A field of ``_NOT_SECRETS`` loses the mark.
    """
    typed = 0
    for schema in list(_every_schema(spec)):
        for name, field in schema.get("properties", {}).items():
            if not isinstance(field, dict):
                continue
            marked = field.pop("writeOnly", False)
            values = field.get("additionalProperties")
            if name in _SECRET_MAPS and isinstance(values, dict):
                # The document allows ``null`` for the map and for a value. The generator types
                # the values only of a plain object, and a field not given is ``None`` anyway.
                field["type"] = "object"
                values.update({"type": "string", "format": "password"})
                typed += 1
            elif marked and name not in _NOT_SECRETS:
                kinds = field.get("type")
                if "string" not in (kinds if isinstance(kinds, list) else [kinds]):
                    raise SystemExit(f"the secret {name!r} is no string: {field}")
                field["format"] = "password"
                typed += 1
    return typed


def _order_value_sets(spec: dict[str, Any]) -> int:
    """Write each set of values in one order wherever it stands; return how many were turned.

    The document lists ``on``/``off`` in a hundred places and ``off``/``on`` in three. Python
    up to 3.13 keeps one object for ``Literal["on", "off"] | str`` and for
    ``Literal["off", "on"] | str``, whichever was evaluated first, and 3.14 keeps two: the
    schema of a model then depends on the interpreter and on the order of imports. With one
    order per set there is nothing to differ. The order kept is the one most places use, the
    first met among equals.

    Examples:
        >>> spec = {
        ...     "paths": {},
        ...     "components": {
        ...         "schemas": {
        ...             "A": {"enum": ["on", "off"]},
        ...             "B": {"enum": ["off", "on"]},
        ...             "C": {"enum": ["on", "off"]},
        ...         }
        ...     },
        ... }
        >>> _order_value_sets(spec), spec["components"]["schemas"]["B"]
        (1, {'enum': ['on', 'off']})
    """
    met: dict[frozenset[str], dict[str, int]] = {}
    held = []
    for schema in list(_every_schema(spec)):
        values = schema.get("enum")
        if isinstance(values, list) and len(values) > 1:
            written = [json.dumps(value) for value in values]
            orders = met.setdefault(frozenset(written), {})
            orders[json.dumps(values)] = orders.get(json.dumps(values), 0) + 1
            held.append((schema, frozenset(written)))
    turned = 0
    for schema, key in held:
        kept = json.loads(max(met[key], key=lambda order: met[key][order]))
        if schema["enum"] != kept:
            schema["enum"] = kept
            turned += 1
    return turned


def _keep_whole_numbers(spec: dict[str, Any]) -> int:
    """Read a ``number`` as a whole number or a fraction, whichever it is; return how many.

    JSON has one kind of number and the document says ``number`` for a count of milliseconds
    as for a ratio. Read as a float, the ``300000`` a caller gave would be sent as ``300000.0``
    and a count in a reply printed with a fraction it never had: ycli sends what it was given.
    """
    changed = 0
    for schema in list(_every_schema(spec)):
        kind = schema.get("type")
        if kind == "number":
            schema["type"] = ["integer", "number"]
        elif isinstance(kind, list) and "number" in kind and "integer" not in kind:
            schema["type"] = ["integer", *kind]
        else:
            continue
        changed += 1
    return changed


def _spread_unions(spec: dict[str, Any]) -> int:
    """Write "these fields and one of those" as "one of those, each with these fields"; count them.

    ``allOf: [{name}, {anyOf: [A, B]}]`` becomes ``anyOf: [{name, ...A}, {name, ...B}]``, whether
    the union is written in place or referred to by name, with a discriminator or without. The
    generator does the same, but names every class it makes after the property and numbers them in
    the order it meets them (``ParamModel7``), so a schema added elsewhere would rename them. Each
    member written out here is an object in place, and gets its name from where it stands.
    """

    def objects(schemas: list[dict[str, Any]]) -> list[dict[str, Any]] | None:
        """The objects ``schemas`` are or refer to; ``None`` when one of them is no object."""
        found = [aimed for schema in schemas if (aimed := _target(spec, schema)) is not None]
        whole = len(found) == len(schemas) and all("properties" in aimed for aimed in found)
        return found if whole else None

    spread = 0
    for schema in list(_every_schema(spec)):
        members = schema.get("allOf")
        if not isinstance(members, list):
            continue
        # The union is written in place or referred to by name: the same thing said twice.
        unions: list[dict[str, Any]] = []
        rest: list[dict[str, Any]] = []
        for member in members:
            found = _target(spec, member) or member
            (unions if "anyOf" in found or "oneOf" in found else rest).append(
                found if "anyOf" in found or "oneOf" in found else member
            )
        parts = objects(rest)
        if len(unions) != 1 or parts is None:
            continue
        (union,) = unions
        key = "anyOf" if "anyOf" in union else "oneOf"
        pieces = [objects([*parts, variant]) for variant in union[key]]
        if any(found is None for found in pieces):
            continue
        variants = []
        for found in pieces:
            merged: dict[str, Any] = {"type": "object", "properties": {}, "required": []}
            for piece in found or []:
                merged["properties"].update(copy.deepcopy(piece["properties"]))
                merged["required"] += [
                    name for name in piece.get("required", []) if name not in merged["required"]
                ]
            variants.append(merged)
        del schema["allOf"]
        schema.update({name: copy.deepcopy(value) for name, value in union.items() if name != key})
        # The members are new objects, so a mapping to the old ones no longer holds: each
        # member carries its tag itself, and the discriminator finds it there.
        if isinstance(schema.get("discriminator"), dict):
            schema["discriminator"].pop("mapping", None)
        schema[key] = variants
        spread += 1
    return spread


def _reply_schemas(spec: dict[str, Any]) -> tuple[dict[int, dict[str, Any]], set[int]]:
    """Every schema a reply reaches, by identity, and the identities a request reaches."""

    def reached(kind: str) -> dict[int, dict[str, Any]]:
        found: dict[int, dict[str, Any]] = {}
        pending = [holder["schema"] for _, _, held, holder in _bodies(spec) if held == kind]
        while pending:
            for schema in _schemas(pending.pop()):
                if id(schema) not in found:
                    found[id(schema)] = schema
                    aimed = _target(spec, schema)
                    if aimed is not None and aimed is not schema:
                        pending.append(aimed)
        return found

    return reached("Response"), set(reached("Request"))


def _values(schema: dict[str, Any]) -> list[Any] | None:
    """The one value ``schema`` names, in a list, or ``None`` when it names more or none."""
    if "const" in schema:
        return [schema["const"]]
    values = schema.get("enum")
    return values if isinstance(values, list) and len(values) == 1 else None


def _kind(schema: dict[str, Any]) -> str:
    """What a field holds, for comparing it between the members of a union.

    The description is no part of it, and a field with one value is a field of that value's
    type: ``{"const": true}`` and ``{"type": "boolean"}`` are the same kind.

    Examples:
        >>> _kind({"const": True, "description": "Locked."}) == _kind({"type": "boolean"})
        True
        >>> _kind({"enum": ["auto"]}) == _kind({"enum": ["fixed"]}) == _kind({"type": "string"})
        True
        >>> _kind({"type": "string"}) == _kind({"type": "object", "properties": {}})
        False
    """
    values = _values(schema)
    if values is not None:
        types = {bool: "boolean", str: "string", int: "integer", float: "number"}
        return json.dumps({"type": types.get(type(values[0]), "null")})
    return json.dumps({key: value for key, value in schema.items() if key != "description"})


def _merged_field(schemas: list[dict[str, Any]]) -> dict[str, Any]:
    """One field for the schemas the members of a union give it, all of one kind.

    A member that names the type gives the field as it is. Members that name one value each
    give the set of those values, open to any string (a set of several is opened with every
    other set of the document, a single value here): the field told the members apart, and
    in one object it is a value like any other, which the API may add to. The description is
    the first member's.

    Examples:
        >>> _merged_field([{"const": True, "description": "Locked."}, {"type": "boolean"}])
        {'type': 'boolean', 'description': 'Locked.'}
        >>> _merged_field([{"enum": ["auto"]}, {"enum": ["fixed"]}])
        {'type': 'string', 'enum': ['auto', 'fixed']}
        >>> _merged_field([{"enum": ["NOT_FOUND"]}])
        {'anyOf': [{'enum': ['NOT_FOUND']}, {'type': 'string'}]}
    """
    said = {key: schemas[0][key] for key in ("description",) if key in schemas[0]}
    plain = next((schema for schema in schemas if _values(schema) is None), None)
    if plain is not None:
        return {**{key: value for key, value in plain.items() if key != "description"}, **said}
    values = list(dict.fromkeys(value for schema in schemas for value in _values(schema) or []))
    if not all(isinstance(value, str) for value in values):
        return {**json.loads(_kind(schemas[0])), **said}
    if len(values) > 1:  # a set of several values is opened with every other such set
        return {**said, "type": "string", "enum": values}
    return {**said, "anyOf": [{"enum": values}, {"type": "string"}]}


def _merge_agreeing_replies(spec: dict[str, Any]) -> int:
    """Read a reply's union of objects that nothing tells apart as one object; return how many.

    ``{permissions} or {error}`` has no discriminator and, since nothing is required, no way to
    choose a member: a value fits both. Where every field the members share is of one kind
    (:func:`_kind`), the union says no more than one object with the fields of all of them, and
    that is what is generated (:func:`_merged_field`).

    Two kinds of union stay as they are. One whose members give a name two different types
    (the parameters of an SQL query, the items of a collection): merged, the field would have
    no type. And one a request reaches: there the merged object would let through the fields of
    two members at once.
    """
    merged = 0
    # A merged object holds copies of its members' fields, and a union inside one of them is
    # met again in the copy: pass over the document until a pass merges nothing.
    while (passed := _merge_pass(spec)) > 0:
        merged += passed
    return merged


def _merge_pass(spec: dict[str, Any]) -> int:
    """One pass of :func:`_merge_agreeing_replies`: how many unions it merged."""
    replies, requests = _reply_schemas(spec)
    merged = 0
    for found, schema in replies.items():
        key = next((key for key in ("oneOf", "anyOf") if key in schema), None)
        if key is None or found in requests or "discriminator" in schema:
            continue
        # A member that is ``null`` only says the value may be absent, as every field may.
        members = [
            aimed
            for member in schema[key]
            if (aimed := _target(spec, member)) and aimed.get("type") != "null"
        ]
        if len(members) < 2 or not all("properties" in member for member in members):
            continue
        fields: dict[str, list[dict[str, Any]]] = {}
        for member in members:
            for name, value in member["properties"].items():
                fields.setdefault(name, []).append(value)
        if all(len({_kind(value) for value in given}) == 1 for given in fields.values()):
            del schema[key]
            properties = {
                name: copy.deepcopy(_merged_field(given)) for name, given in fields.items()
            }
            schema.update({"type": "object", "properties": properties})
            merged += 1
    return merged


def _require_discriminators(spec: dict[str, Any]) -> set[int]:
    """Make each union's discriminator a required property of its members; return those nodes.

    pydantic builds a discriminated union only from members that always carry the tag, and
    DataLens leaves it optional in most of them.
    """
    tags: set[int] = set()
    for union in list(_every_schema(spec)):
        discriminator = union.get("discriminator")
        if not isinstance(discriminator, dict):
            continue
        name = discriminator["propertyName"]
        for member in [*union.get("oneOf", []), *union.get("anyOf", [])]:
            aimed = _target(spec, member)
            if aimed is None or name not in aimed.get("properties", {}):
                continue
            tags.add(id(aimed["properties"][name]))
            if name not in aimed.get("required", []):
                aimed.setdefault("required", []).append(name)
    return tags


def _tag(union: dict[str, Any], members: list[dict[str, Any]]) -> str | None:
    """The field that tells the members of ``union`` apart, or ``None`` when none does.

    It is the discriminator the document names, else the first field that has one value in
    every member and a different one in each (``entity`` of an item of a collection).

    Examples:
        >>> entry = {"properties": {"scope": {"enum": ["x"]}, "entity": {"enum": ["entry"]}}}
        >>> book = {"properties": {"scope": {"enum": ["x"]}, "entity": {"enum": ["workbook"]}}}
        >>> _tag({}, [entry, book])
        'entity'
        >>> _tag({"discriminator": {"propertyName": "type"}}, [entry, book])
        'type'
        >>> _tag({}, [entry, {"properties": {"title": {"type": "string"}}}]) is None
        True
    """
    discriminator = union.get("discriminator")
    if isinstance(discriminator, dict):
        return discriminator["propertyName"]
    for name in members[0]["properties"]:
        told = [_values(member["properties"].get(name, {})) for member in members]
        if all(told) and len({json.dumps(values) for values in told}) == len(members):
            return name
    return None


def _write_tags(spec: dict[str, Any], union: dict[str, Any], tags: set[int]) -> None:
    """Write into each member of ``union`` the tag its discriminator maps to it.

    A member may leave its tag to the mapping, or name it as any string. Without the
    discriminator nothing else says which kind the member is, so the mapping is written into
    the member: a required field with the values that lead to it, added to ``tags``.
    """
    discriminator = union["discriminator"]
    name = discriminator["propertyName"]
    told: dict[int, tuple[dict[str, Any], list[str]]] = {}
    for value, ref in discriminator.get("mapping", {}).items():
        aimed = _target(spec, {"$ref": ref})
        if aimed is not None:
            told.setdefault(id(aimed), (aimed, []))[1].append(value)
    for aimed, values in told.values():
        field = aimed.setdefault("properties", {}).setdefault(name, {})
        said = {key: field[key] for key in ("description",) if key in field}
        field.clear()
        field.update({**said, "type": "string", "enum": values})
        tags.add(id(field))
        if name not in aimed.setdefault("required", []):
            aimed["required"].append(name)


def _spare_members(spec: dict[str, Any], tags: set[int]) -> int:
    """Give every union of kinds a spare open member; return how many.

    The document is wrong about what DataLens sends: a source of a dataset comes with a kind
    it does not list, a field with a type it does not name. A union of closed kinds refuses
    the whole reply for one such object. So the union is read softly (#391): a value that
    fits no member is the spare one: an open object with no field of its own, which keeps
    every key as it came.

    The discriminator goes with it: a discriminated union refuses an unknown tag before any
    member is tried. Its members still require their tag (:func:`_write_tags`), so a value
    fits one member at most, and the spare, which declares nothing, is chosen only when none
    fits.

    It holds for a request as for a reply (#444): DataLens takes kinds its document does not
    list (a source of the kind ``GSHEETS_V2``), and a request ycli refused could not be
    sent at all. One union is left as it is: a union only a request reaches whose members
    nothing tells apart. There is no kind to be unknown there, and a spare member would
    make every object fit.
    """
    replies, _ = _reply_schemas(spec)
    schemas = spec["components"]["schemas"]
    if SPARE in schemas:
        raise SystemExit(f"the specification has a schema named {SPARE!r} already")
    spare = {"type": "object", "description": _SPARE_SAYS}
    spared = 0
    for union in list(_every_schema(spec)):
        key = next((key for key in ("oneOf", "anyOf") if key in union), None)
        if key is None:
            continue
        members = [
            aimed
            for member in union[key]
            if (aimed := _target(spec, member)) and "properties" in aimed
        ]
        if len(members) < 2:
            continue
        tag = _tag(union, members)
        if tag is None and id(union) not in replies:
            continue
        schemas.setdefault(SPARE, spare)
        if isinstance(union.get("discriminator"), dict):
            _write_tags(spec, union, tags)
            del union["discriminator"]
        union["anyOf"] = [*union.pop(key), {"$ref": _REF + SPARE}]
        spared += 1
    return spared


def _open_value_sets(spec: dict[str, Any], keep: set[int]) -> None:
    """A closed set of several string values also takes any string, except a union's tag.

    The API adds values without notice, and a reply with a new one must still parse
    (conventions, "A field with a set of values"). A single value is a tag, not a set; a set
    that also allows ``null`` is still a set of strings.
    """
    for schema in list(_every_schema(spec)):
        values = schema.get("enum")
        if not isinstance(values, list) or id(schema) in keep:
            continue
        strings = [value for value in values if isinstance(value, str)]
        if len(strings) > 1 and all(value is None for value in values if value not in strings):
            closed = {key: schema.pop(key) for key in ("enum", "type") if key in schema}
            schema["anyOf"] = [closed, {"type": "string"}]


def _join_envelope_parts(spec: dict[str, Any]) -> int:
    """Write a request envelope given in parts ("all of these") as one object; return how many.

    ``createWizardChart`` takes its own fields and the fields every entry is placed by, and
    the document writes that as two parts. The generator makes a class that inherits one part,
    and it is not seen as an envelope: it stays open, and its fields are not the arguments of
    the operation (#371). Joined, it is an envelope like any other. A part that is not a plain
    object (a union) leaves the envelope as it is.
    """
    joined = 0
    for _, _, kind, holder in _bodies(spec):
        envelope = _target(spec, holder["schema"])
        if kind != "Request" or envelope is None or "allOf" not in envelope:
            continue
        aimed = [_target(spec, part) for part in envelope["allOf"]]
        parts = [part for part in aimed if part is not None and "properties" in part]
        if len(parts) != len(aimed):
            continue
        properties: dict[str, Any] = {}
        required: list[str] = []
        for part in parts:
            properties.update(copy.deepcopy(part["properties"]))
            required += [name for name in part.get("required", []) if name not in required]
        del envelope["allOf"]
        envelope.update({"type": "object", "properties": properties, "required": required})
        joined += 1
    return joined


def _close_only_requests(spec: dict[str, Any]) -> None:
    """Only the envelope of a request refuses an unknown field; a reply is read as it comes.

    The server refuses an unknown key of a request, and a field mistyped in an argument should
    fail before it is sent. An envelope the document itself leaves open stays open.
    """
    for schema in list(_every_schema(spec)):
        if schema.get("additionalProperties") is False:
            del schema["additionalProperties"]
    for _, _, kind, holder in _bodies(spec):
        envelope = _target(spec, holder["schema"])
        if kind == "Request" and envelope and "properties" in envelope:
            envelope.setdefault("additionalProperties", False)


def _one_value(schema: object) -> bool:
    """Whether ``schema`` takes one value only: ``{"enum": ["entry"]}`` or ``{"const": 1}``."""
    if not isinstance(schema, dict):
        return False
    values = schema.get("enum")
    return "const" in schema or (isinstance(values, list) and len(values) == 1)


def _require_only_kinds(spec: dict[str, Any], keep: set[int]) -> int:
    """Require only what tells a kind and the arguments of an operation; return how many went.

    The document calls fields required that DataLens leaves out: ``getWorkbook`` answers without
    ``permissions`` unless the request asks for them, and a model that required the field would
    refuse every such reply. Most objects are both read and sent back (read, change, write), so
    one class serves both ways and requires nothing: what a request lacks DataLens says itself.
    Two things stay required. A field that tells which member of a union a value is: a
    discriminator, and a field with one value only (``entity`` of an item of a collection, where
    the document names no discriminator). And the top level of a request, whose fields are the
    arguments of the operation.
    """
    envelopes = {
        id(_target(spec, holder["schema"]))
        for _, _, kind, holder in _bodies(spec)
        if kind == "Request"
    }
    changed = 0
    for schema in list(_every_schema(spec)):
        required = schema.get("required")
        if id(schema) in envelopes or not isinstance(required, list):
            continue
        properties = schema.get("properties", {})
        tags = [
            name
            for name in required
            if id(properties.get(name)) in keep or _one_value(properties.get(name))
        ]
        changed += len(required) - len(tags)
        schema["required"] = tags
    return changed


def _name_every_object(spec: dict[str, Any]) -> None:
    """Give every object written in place a name of its own, made from where it stands.

    The generator would name it after its property and number the clashes in the order it
    meets them, so a schema added elsewhere would rename classes that did not change. A name
    made from the path (``DashboardDataTabsItem``) moves only when its own parents do.
    """
    schemas = spec["components"]["schemas"]

    def unique(name: str) -> str:
        found, number = name, 1
        while found in schemas:
            number += 1
            found = f"{name}{number}"
        return found

    def descend(schema: dict[str, Any], name: str) -> None:
        for suffix, child, holder, key in list(_children(schema)):
            if "$ref" in child:
                continue
            # A member of ``allOf`` is a part of this object, not an object of its own. An
            # object made of parts is one, though: left unnamed, the generator would call it
            # ``Entry``, ``EntryModel``, ``EntryModel1`` in the order it meets them.
            part = holder is schema.get("allOf")
            if ("properties" in child or "allOf" in child) and not part:
                named = unique(name + suffix)
                schemas[named] = child
                holder[key] = {"$ref": _REF + named}
                descend(child, named)
            else:
                descend(child, name if part else name + suffix)

    for name, _, kind, holder in list(_bodies(spec)):
        if "$ref" not in holder["schema"]:
            named = unique(name[:1].upper() + name[1:] + kind)
            schemas[named] = holder["schema"]
            holder["schema"] = {"$ref": _REF + named}
    for name in list(schemas):
        descend(schemas[name], name)


def _references(schema: dict[str, Any]) -> list[str]:
    """The names of the component schemas ``schema`` refers to, at any depth."""
    return [
        found["$ref"].removeprefix(_REF)
        for found in _schemas(schema)
        if isinstance(found.get("$ref"), str)
    ]


def _sections(spec: dict[str, Any]) -> dict[str, str]:
    """The module of each schema an operation reaches: its one section, else ``shared``.

    A schema no operation reaches gets no module: nothing can send or receive it.
    """
    schemas = spec["components"]["schemas"]
    reached: dict[str, set[str]] = {}
    for _, tag, _, holder in _bodies(spec):
        seen: set[str] = set()
        pending = _references(holder["schema"])
        while pending:
            name = pending.pop()
            if name not in seen:
                seen.add(name)
                pending += _references(schemas[name])
        for name in seen:
            reached.setdefault(name, set()).add(tag)
    return {
        name: _snake(next(iter(tags))) if len(tags) == 1 else SHARED
        for name, tags in reached.items()
    }


def prepare(spec: dict[str, Any]) -> dict[str, Any]:
    """The specification rewritten so that the generated models follow ycli's rules.

    Args:
        spec: The OpenAPI document as DataLens publishes it.

    Returns:
        A copy with no generator directives and no defaults, in which a set of values has one
        order wherever it stands, a number is read whole
        or fractional as it comes, "these fields and one of
        those" is written as its members, a request envelope given in parts is one object,
        a reply's union of objects that nothing tells apart is
        one object, a union's discriminator is
        required in its members, a union of kinds has a spare open member,
        a set of string values is open, nothing else is required
        below the top level of a request, only a request envelope is closed to unknown fields,
        every object has a name made from its place, a schema no
        operation reaches is gone, and each schema is named ``<section>.<Name>``.

    Raises:
        SystemExit: A name of the document cannot be a module or a class name.

    Examples:
        >>> spec = {
        ...     "components": {"schemas": {"Mode": {"type": "string", "enum": ["a", "b"]}}},
        ...     "paths": {
        ...         "/rpc/getX": {
        ...             "post": {
        ...                 "tags": ["Things"],
        ...                 "responses": {
        ...                     "200": {
        ...                         "content": {
        ...                             "application/json": {
        ...                                 "schema": {"$ref": "#/components/schemas/Mode"}
        ...                             }
        ...                         }
        ...                     }
        ...                 },
        ...             }
        ...         }
        ...     },
        ... }
        >>> prepare(spec)["components"]["schemas"]
        {'things.Mode': {'anyOf': [{'enum': ['a', 'b'], 'type': 'string'}, {'type': 'string'}]}}
    """
    spec = copy.deepcopy(spec)
    _plain(spec)
    _order_value_sets(spec)
    _type_secrets(spec)
    _keep_whole_numbers(spec)
    _spread_unions(spec)
    _join_envelope_parts(spec)
    _merge_agreeing_replies(spec)
    tags = _require_discriminators(spec)
    _spare_members(spec, tags)
    _open_value_sets(spec, keep=tags)
    _require_only_kinds(spec, keep=tags)
    _close_only_requests(spec)
    _name_every_object(spec)
    section = _sections(spec)
    schemas = {
        name: schema for name, schema in spec["components"]["schemas"].items() if name in section
    }
    for name in section:
        # One module per section, one class per schema: a dot would make a package of either.
        if not re.fullmatch(r"\w+", name) or not re.fullmatch(r"\w+", section[name]):
            raise SystemExit(f"the specification names a schema or a section {name!r}")

    def moved(ref: str) -> str:
        name = ref.removeprefix(_REF)
        return f"{_REF}{section[name]}.{name}"

    spec["components"]["schemas"] = schemas
    for schema in list(_every_schema(spec)):
        if isinstance(schema.get("$ref"), str):
            schema["$ref"] = moved(schema["$ref"])
        mapping = schema.get("discriminator", {}).get("mapping")
        if isinstance(mapping, dict):
            schema["discriminator"]["mapping"] = {
                tag: moved(ref) if ref.startswith(_REF) else ref for tag, ref in mapping.items()
            }
    spec["components"]["schemas"] = {
        f"{section[name]}.{name}": schema for name, schema in schemas.items()
    }
    return spec


_QUIET = "hide_input_in_errors"


def _quiet_root_models(text: str) -> str:
    r"""Make every ``RootModel`` of a module keep its input out of the text of its errors.

    A value that fails validation is quoted in the error, and the value may be a connection
    with its password: a union is refused by its tag before any ``SecretStr`` is built. The
    models take the setting from ``APIModel``; a ``RootModel`` has no such base, so it is
    given in the class statement, which needs no import.

    Examples:
        >>> _quiet_root_models("class Kind(RootModel[A | B]):\n    root: A | B\n")
        'class Kind(RootModel[A | B], hide_input_in_errors=True):\n    root: A | B\n'
        >>> _quiet_root_models(_quiet_root_models("class Kind(RootModel[A]):\n    root: A\n"))
        'class Kind(RootModel[A], hide_input_in_errors=True):\n    root: A\n'
    """
    lines = text.splitlines(keepends=True)
    for node in ast.parse(text).body:
        if not isinstance(node, ast.ClassDef) or any(key.arg == _QUIET for key in node.keywords):
            continue
        for base in node.bases:
            root = base.value if isinstance(base, ast.Subscript) else base
            if isinstance(root, ast.Name) and root.id == "RootModel":
                last = node.bases[-1]
                row, column = (last.end_lineno or 0) - 1, last.end_col_offset or 0
                lines[row] = f"{lines[row][:column]}, {_QUIET}=True{lines[row][column:]}"
    return "".join(lines)


def finish(text: str) -> str:
    """One generated module as it is committed, before formatting: header and request bases.

    A model the generator closed to unknown fields is the envelope of a request (``prepare``
    closes nothing else), so it takes ``RequestBody``, which is closed already. Running it on
    its own result changes nothing.

    Args:
        text: The module as the generator wrote it, or as this function left it.

    Returns:
        The module with ycli's header and with ``RequestBody`` for the request envelopes.

    Examples:
        >>> module = '''# generated by datamodel-codegen:
        ... #   filename:  spec.json
        ... from ycli.yandex.models import APIModel
        ... class GetArgs(APIModel):
        ...     model_config = ConfigDict(
        ...         extra="forbid",
        ...     )
        ...     dashboard_id: str
        ... '''
        >>> print(finish(module).split("by hand.")[1])
        <BLANKLINE>
        from ycli.yandex.models import APIModel, RequestBody
        class GetArgs(RequestBody):
            dashboard_id: str
        <BLANKLINE>
        >>> finish(finish(module)) == finish(module)
        True
    """
    text = _GENERATOR_HEADER.sub("", text)
    if not text.startswith(HEADER):
        text = HEADER + text
    text, closed = _CLOSED_MODEL.subn(r"class \1(RequestBody):\n\2", text)
    if closed:
        text = text.replace(
            _MODELS_IMPORT, "from ycli.yandex.models import APIModel, RequestBody\n"
        )
    return _quiet_root_models(text)


def _ruff(text: str, name: str) -> str:
    """``text`` as ruff leaves the generated module ``name``: safe fixes, then the formatter.

    The file is named by its committed path, so the settings of that path apply wherever the
    text is being written.
    """
    path = _HOME / name
    for arguments in (["check", "--fix-only", "--quiet"], ["format", "--quiet"]):
        text = subprocess.run(
            [sys.executable, "-m", "ruff", *arguments, "--stdin-filename", str(path), "-"],
            input=text,
            capture_output=True,
            text=True,
            check=True,
            cwd=ROOT,
        ).stdout
    return text


def foreign(text: str) -> list[str]:
    r"""What in a generated module is not a plain model: the reason it may not be imported.

    The modules are written from a downloaded document and imported by every test run, so each
    must be nothing but imports from a few known modules and classes that declare fields. A
    module that imports anything else, inherits from a class of another package, or runs any
    code but ``Field(...)`` and ``ConfigDict(...)`` is refused.

    Examples:
        >>> foreign("from subprocess import Popen\nclass Chart(Popen):\n    pass\n")
        ['line 1: imports subprocess', 'line 2: Chart inherits from Popen']
        >>> foreign("from pydantic import Field\nclass A(APIModel):\n    x: int = Field(1)\n")
        []
    """
    found = []
    tree = ast.parse(text)
    own = {node.name for node in tree.body if isinstance(node, ast.ClassDef)}
    sections: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.ImportFrom):
            if node.level == 1:  # a sibling module of the generated package, or a class of one
                own |= {alias.asname or alias.name for alias in node.names}
                sections |= {alias.asname or alias.name for alias in node.names}
            elif node.level or node.module not in _MODULES:
                found.append(f"line {node.lineno}: imports {'.' * node.level}{node.module or ''}")
        elif isinstance(node, ast.ClassDef):
            for base in node.bases:
                root = base.value if isinstance(base, ast.Subscript) else base
                named = isinstance(root, ast.Name) and root.id in own | _BASES
                sibling = (
                    isinstance(root, ast.Attribute)
                    and isinstance(root.value, ast.Name)
                    and root.value.id in sections
                )
                if not (named or sibling):
                    found.append(
                        f"line {node.lineno}: {node.name} inherits from {ast.unparse(base)}"
                    )
            found += [
                f"line {item.lineno}: {node.name} holds {type(item).__name__}"
                for item in node.body
                if not isinstance(item, ast.AnnAssign | ast.Assign | ast.Pass)
                and not (isinstance(item, ast.Expr) and isinstance(item.value, ast.Constant))
            ]
            found += [
                f"line {call.lineno}: {node.name} calls {ast.unparse(call.func)}"
                for call in ast.walk(node)
                if isinstance(call, ast.Call) and ast.unparse(call.func) not in _CALLS
            ]
        else:
            found.append(f"line {node.lineno}: a statement that is no import and no class")
    return found


def generate(spec: dict[str, Any]) -> dict[str, str]:
    """Every module of the generated layer for ``spec``, by its file name.

    Raises:
        SystemExit: The generator wrote a package instead of a module, or a module that is not
            a plain model (see :func:`foreign`).
    """
    with tempfile.TemporaryDirectory() as scratch:
        source = Path(scratch) / "spec.json"
        source.write_text(json.dumps(prepare(spec)), encoding="utf-8")
        output = Path(scratch) / "schemas"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                *("--input", str(source), "--input-file-type", "openapi"),
                *("--output", str(output), "--output-model-type", "pydantic_v2.BaseModel"),
                *("--target-python-version", "3.12", "--formatters", "builtin"),
                *("--base-class", "ycli.yandex.models.APIModel", "--openapi-scopes", "schemas"),
                *("--enum-field-as-literal", "all", "--treat-dot-as-module"),
                "--use-union-operator",
                "--use-standard-collections",
                "--use-double-quotes",
                "--use-default-kwarg",
                "--use-schema-description",
                "--snake-case-field",
                "--field-constraints",
                "--disable-timestamp",
                "--disable-future-imports",
            ],
            check=True,
            cwd=ROOT,
        )
        nested = sorted(path.name for path in output.iterdir() if path.is_dir())
        if nested:
            raise SystemExit(f"the generator wrote packages, not modules: {nested}")
        modules = {
            path.name: _ruff(finish(path.read_text(encoding="utf-8")), path.name)
            for path in sorted(output.glob("*.py"))
        }
    refused = [f"{name}: {why}" for name, text in modules.items() for why in foreign(text)]
    if refused:
        raise SystemExit("the generated code is not plain models:\n" + "\n".join(refused))
    return modules


def _digest(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def manifest(modules: Mapping[str, str]) -> str:
    """The record of a generation: one ``<sha256>  <file name>`` line per module."""
    return "".join(f"{_digest(text)}  {name}\n" for name, text in sorted(modules.items()))


def edited_by_hand() -> list[str]:
    """How the committed layer differs from what the script last wrote (empty: it does not).

    The script records every file it writes with its checksum (``MANIFEST``). A file changed,
    added or removed without the script shows here, and so does a file that is not plain
    models. It reads no specification. What it cannot tell: that the record itself was edited
    to match, which a reviewer sees as a change of two files with no change of the script.
    """
    recorded = {}
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        digest, _, name = line.partition("  ")
        recorded[name] = digest
    committed = {
        path.name: path.read_text(encoding="utf-8") for path in sorted(SCHEMAS.glob("*.py"))
    }
    found = [
        f"{name}: recorded, not in the directory"
        for name in sorted(recorded.keys() - committed.keys())
    ]
    for name, text in committed.items():
        if name not in recorded:
            found.append(f"{name}: not written by the script")
        elif _digest(text) != recorded[name]:
            found.append(f"{name}: differs from what the script wrote")
        found += [f"{name}: {why}" for why in foreign(text)]
    found += [
        f"{path.name}: a directory"
        for path in sorted(SCHEMAS.iterdir())
        if path.is_dir() and path.name != "__pycache__"
    ]
    return found


def _published() -> dict[str, Any]:
    import httpx2

    return httpx2.get(SPEC_URL, timeout=60, follow_redirects=True).raise_for_status().json()


def main(argv: list[str] | None = None) -> int:
    """Write the generated layer, or report what a check found and exit 1."""
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--spec", type=Path, help="a saved copy of the specification")
    parser.add_argument("--check", action="store_true", help="exit 1 if a file was edited by hand")
    parser.add_argument("--live", action="store_true", help="with --check: compare with DataLens")
    args = parser.parse_args(argv)
    if args.check and not args.live:
        edited = edited_by_hand()
        for line in edited:
            print(f"not what the script wrote: {line}", file=sys.stderr)
        return 1 if edited else 0
    spec = json.loads(args.spec.read_text(encoding="utf-8")) if args.spec else _published()
    modules = generate(spec)
    committed = {path.name: path.read_text(encoding="utf-8") for path in SCHEMAS.glob("*.py")}
    if args.check:
        stale = sorted(
            name
            for name in modules.keys() | committed.keys()
            if modules.get(name) != committed.get(name)
        )
        for name in stale:
            print(f"differs from the published specification: {name}")
        return 1 if stale else 0
    SCHEMAS.mkdir(parents=True, exist_ok=True)
    for name in committed.keys() - modules.keys():
        (SCHEMAS / name).unlink()
    for name, text in modules.items():
        (SCHEMAS / name).write_text(text, encoding="utf-8")
    MANIFEST.write_text(manifest(modules), encoding="utf-8")
    print(f"{len(modules)} modules, {sum(text.count(chr(10)) for text in modules.values())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
