#!/usr/bin/env python
"""Generate README's Coverage section from the live code (a reproducible artifact).

Introspects the three domain clients **offline** (dummy credentials — constructing a client
builds only a ``requests.Session``, no HTTP) plus the committed public-surface data (the CLI
tree from :func:`tests.snapshots._surface.cli_tree` and the MCP tool-name snapshot
``tests/snapshots/mcp_tools.txt``) and emits the Markdown block README embeds between its
``COVERAGE:START`` / ``COVERAGE:END`` markers.

Per resource it reports the wrapped SDK operations (public methods on the resource client
class, in source order) and whether that resource is reachable via the CLI and via at least
one MCP tool. MCP mirrors the SDK with honest annotations (ARCH-3): reads carry
``readOnlyHint``, writes carry explicit destructive/idempotent hints; a resource with no MCP
tool yet shows ``—`` in the MCP column.

Usage::

    python scripts/gen_coverage.py            # print the block to stdout
    python scripts/gen_coverage.py --write    # splice it into README.md
    python scripts/gen_coverage.py --check     # exit 1 if README's block is stale

``--check`` powers ``tests/test_coverage_readme.py`` so the tables can never silently drift
from the code.
"""

from __future__ import annotations

import argparse
import inspect
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import uplink.builder

from ycli.yandex.base import BaseYandex
from ycli.yandex.forms.client import FormsClient
from ycli.yandex.tracker.client import TrackerClient
from ycli.yandex.wiki.client import WikiClient

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
MCP_TOOLS = ROOT / "tests" / "snapshots" / "mcp_tools.txt"

START = "<!-- COVERAGE:START (generated by scripts/gen_coverage.py — do not edit by hand) -->"
END = "<!-- COVERAGE:END -->"

YES = "✅"
NO = "—"

# Per-domain category → resource-attribute grouping. Every resource on a client must appear
# in exactly one group; a resource that is missing here lands in a trailing "Other" group so
# the omission is visible rather than silently dropped.
TRACKER_CATEGORIES: list[tuple[str, list[str]]] = [
    (
        "Issues & work items",
        [
            "issues",
            "comments",
            "links",
            "transitions",
            "worklog",
            "changelog",
            "checklists",
            "attachments",
            "remotelinks",
        ],
    ),
    ("Agile boards", ["boards", "sprints", "columns"]),
    ("Dictionaries", ["priorities", "statuses", "resolutions", "issuetypes", "linktypes"]),
    ("Fields, queues & structure", ["fields", "localfields", "components", "queues"]),
    ("Automation & bulk", ["macros", "triggers", "autoactions", "dashboards", "bulk", "import_"]),
    ("Entities, users & search", ["entities", "users", "applications", "filters", "me"]),
]
WIKI_CATEGORIES: list[tuple[str, list[str]]] = [
    ("Pages", ["pages", "resources", "recovery"]),
    ("Collaboration", ["comments", "attachments"]),
    ("Grids (dynamic tables)", ["grids"]),
    ("Async & uploads", ["operations", "uploadsessions"]),
    ("Identity", ["me"]),
]
FORMS_CATEGORIES: list[tuple[str, list[str]]] = [
    ("Surveys & questions", ["surveys", "questions"]),
    ("Responses & export", ["answers", "operations"]),
    ("Distribution", ["keysets", "filling"]),
    ("Media", ["files", "images"]),
    ("Identity", ["me"]),
]


@dataclass(frozen=True)
class DomainSpec:
    """One domain to document: its heading, CLI/MCP namespace slug, live client, and groups."""

    title: str
    slug: str
    client: object
    categories: list[tuple[str, list[str]]]


@dataclass(frozen=True)
class ResourceRow:
    """A single table row: a resource, its wrapped ops, and per-surface reachability."""

    display: str
    operations: tuple[str, ...]
    has_cli: bool
    has_mcp: bool


@dataclass(frozen=True)
class DomainReport:
    """A rendered domain: its category groups (each a list of rows) plus headline totals."""

    title: str
    groups: list[tuple[str, list[ResourceRow]]]
    resource_count: int
    operation_count: int
    mcp_tool_count: int


def _cli_paths() -> list[str]:
    """Every CLI command path (space-joined), via the shared surface enumerator."""
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from tests.snapshots._surface import cli_tree

    return cli_tree()


def _mcp_tool_names() -> list[str]:
    """Every MCP tool name, from the committed snapshot."""
    return MCP_TOOLS.read_text(encoding="utf-8").split()


def _display_name(attribute: str) -> str:
    """Resource attribute → its CLI/MCP/display name (``import_`` → ``import``)."""
    return attribute[:-1] if attribute.endswith("_") else attribute


def _sdk_operations(resource: object) -> tuple[str, ...]:
    """Public op names defined on the resource client class itself, in source order.

    Both hand-written methods (plain functions) and uplink-decorated endpoints
    (``ConsumerMethod`` descriptors) count; dunder and leading-underscore internals do not.
    """
    ops: list[str] = []
    for name, member in type(resource).__dict__.items():
        if name.startswith("_"):
            continue
        if inspect.isfunction(member) or isinstance(member, uplink.builder.ConsumerMethod):
            ops.append(name)
    return tuple(ops)


def _cli_ops(slug: str, display: str, paths: list[str]) -> list[str]:
    """CLI sub-command remainders under ``<slug> <display>`` (segment-exact prefix match)."""
    prefix = [slug, display]
    return [" ".join(s[2:]) for path in paths if (s := path.split())[:2] == prefix and len(s) > 2]


def _mcp_tools(slug: str, display: str, tools: list[str]) -> list[str]:
    """MCP tool names under the ``<slug>_<display>_`` namespace."""
    prefix = f"{slug}_{display}_"
    return [tool for tool in tools if tool.startswith(prefix)]


def _report(spec: DomainSpec, paths: list[str], tools: list[str]) -> DomainReport:
    """Build a fully-computed :class:`DomainReport` from a live client + surface data."""
    discovered = {
        name for name, value in vars(spec.client).items() if isinstance(value, BaseYandex)
    }
    placed: set[str] = set()
    groups: list[tuple[str, list[ResourceRow]]] = []
    operation_count = 0

    for heading, attributes in spec.categories:
        rows: list[ResourceRow] = []
        for attribute in attributes:
            resource = getattr(spec.client, attribute)
            if not isinstance(resource, BaseYandex):
                raise SystemExit(f"gen_coverage: {spec.slug}.{attribute} is not a resource client")
            placed.add(attribute)
            display = _display_name(attribute)
            operations = _sdk_operations(resource)
            if not operations:
                raise SystemExit(f"gen_coverage: {spec.slug}.{attribute} exposes no SDK operations")
            operation_count += len(operations)
            rows.append(
                ResourceRow(
                    display=display,
                    operations=operations,
                    has_cli=bool(_cli_ops(spec.slug, display, paths)),
                    has_mcp=bool(_mcp_tools(spec.slug, display, tools)),
                )
            )
        groups.append((heading, rows))

    unplaced = sorted(discovered - placed)
    if unplaced:
        rows = []
        for attribute in unplaced:
            resource = getattr(spec.client, attribute)
            display = _display_name(attribute)
            operations = _sdk_operations(resource)
            operation_count += len(operations)
            rows.append(
                ResourceRow(
                    display=display,
                    operations=operations,
                    has_cli=bool(_cli_ops(spec.slug, display, paths)),
                    has_mcp=bool(_mcp_tools(spec.slug, display, tools)),
                )
            )
        groups.append(("Other", rows))

    return DomainReport(
        title=spec.title,
        groups=groups,
        resource_count=len(discovered),
        operation_count=operation_count,
        mcp_tool_count=sum(1 for tool in tools if tool.startswith(f"{spec.slug}_")),
    )


def _render_table(rows: list[ResourceRow]) -> list[str]:
    """The Markdown lines for one resource-group table."""
    lines = [
        "| Resource | Operations | SDK | CLI | MCP |",
        "|----------|------------|:---:|:---:|:---:|",
    ]
    for row in rows:
        operations = " · ".join(row.operations)
        cli = YES if row.has_cli else NO
        mcp = YES if row.has_mcp else NO
        lines.append(f"| {row.display} | {operations} | {YES} | {cli} | {mcp} |")
    return lines


def _render(reports: list[DomainReport]) -> str:
    """The full inner Markdown block (without the surrounding markers)."""
    resources = sum(report.resource_count for report in reports)
    operations = sum(report.operation_count for report in reports)
    mcp_tools = sum(report.mcp_tool_count for report in reports)

    lines = [
        "## Coverage",
        "",
        f"`ycli` wraps the **near-complete public REST API** of Tracker, Wiki, and Forms — "
        f"{operations} operations across {resources} resources, every one reachable from the "
        f"**Python SDK** and the **CLI**, plus {mcp_tools} **MCP** tools for agents.",
        "",
        "> **Legend** — operations ship on **SDK + CLI**, and the **MCP** server mirrors them "
        "with honest annotations: reads carry `readOnlyHint`, writes carry explicit "
        "destructive/idempotent hints, and `ycli mcp start --read-only` serves the reads-only "
        "view. In each table **SDK** and **CLI** mean the operation is wrapped on that "
        f"surface; **MCP** is {YES} when the resource exposes at least one MCP tool. These "
        "tables are generated from the code by "
        "[`scripts/gen_coverage.py`](scripts/gen_coverage.py) — do not edit by hand.",
    ]
    for report in reports:
        lines += [
            "",
            f"### {report.title}",
            "",
            f"**{report.resource_count} resources · {report.operation_count} operations · "
            f"{report.mcp_tool_count} MCP tools**",
        ]
        for heading, rows in report.groups:
            lines += ["", f"#### {heading}", "", *_render_table(rows)]
    lines += [
        "",
        "See [`docs/api-coverage.md`](docs/api-coverage.md) for the intentional exclusions "
        "(UI-only endpoints with no public REST API) and per-method notes.",
    ]
    return "\n".join(lines)


def build_block() -> str:
    """The complete marker-wrapped Coverage block that README embeds."""
    paths = _cli_paths()
    tools = _mcp_tool_names()
    specs = [
        DomainSpec(
            "Tracker",
            "tracker",
            TrackerClient(oauth_token="x", organization_id="x"),
            TRACKER_CATEGORIES,
        ),
        DomainSpec(
            "Wiki", "wiki", WikiClient(oauth_token="x", organization_id="x"), WIKI_CATEGORIES
        ),
        DomainSpec(
            "Forms", "forms", FormsClient(oauth_token="x", organization_id="x"), FORMS_CATEGORIES
        ),
    ]
    reports = [_report(spec, paths, tools) for spec in specs]
    return f"{START}\n{_render(reports)}\n{END}"


def splice(text: str, block: str) -> str:
    """Return ``text`` with its Coverage block replaced by ``block``.

    If the markers already exist, replace between them; otherwise (first run) replace the
    legacy ``## What's covered`` section that sits just before ``## Configure``.
    """
    if START in text and END in text:
        return text[: text.index(START)] + block + text[text.index(END) + len(END) :]
    pattern = re.compile(r"## What's covered.*?(?=\n## Configure)", re.DOTALL)
    if not pattern.search(text):
        raise SystemExit("gen_coverage: could not locate the coverage section to replace")
    return pattern.sub(lambda _match: block + "\n", text)


def main(argv: list[str] | None = None) -> int:
    """CLI entry point; see the module docstring for the three modes."""
    parser = argparse.ArgumentParser(description="Generate README's Coverage section.")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true", help="splice the block into README.md")
    group.add_argument("--check", action="store_true", help="exit 1 if README's block is stale")
    args = parser.parse_args(argv)

    block = build_block()
    if args.write:
        README.write_text(splice(README.read_text(encoding="utf-8"), block), encoding="utf-8")
        return 0
    if args.check:
        current = README.read_text(encoding="utf-8")
        if current != splice(current, block):
            print(
                "README coverage block is stale; run: uv run python scripts/gen_coverage.py "
                "--write",
                file=sys.stderr,
            )
            return 1
        return 0
    print(block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
